// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paskoocheh.proto

package org.asl19.paskoocheh;

/**
 * Protobuf type {@code org.asl19.paskoocheh.Config}
 */
public final class Config extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.asl19.paskoocheh.Config)
    ConfigOrBuilder {
  // Use Config.newBuilder() to construct.
  private Config(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Config(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Config defaultInstance;
  public static Config getDefaultInstance() {
    return defaultInstance;
  }

  public Config getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Config(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            bucket_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            version_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              images_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            images_.add(bs);
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              platforms_ = new java.util.ArrayList<org.asl19.paskoocheh.Platform>();
              mutable_bitField0_ |= 0x00000008;
            }
            platforms_.add(input.readMessage(org.asl19.paskoocheh.Platform.PARSER, extensionRegistry));
            break;
          }
          case 162: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              update_ = new java.util.ArrayList<org.asl19.paskoocheh.Message>();
              mutable_bitField0_ |= 0x00000010;
            }
            update_.add(input.readMessage(org.asl19.paskoocheh.Message.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        images_ = images_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        platforms_ = java.util.Collections.unmodifiableList(platforms_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        update_ = java.util.Collections.unmodifiableList(update_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Config_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Config_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.asl19.paskoocheh.Config.class, org.asl19.paskoocheh.Config.Builder.class);
  }

  public static com.google.protobuf.Parser<Config> PARSER =
      new com.google.protobuf.AbstractParser<Config>() {
    public Config parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Config(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Config> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int BUCKET_FIELD_NUMBER = 1;
  private java.lang.Object bucket_;
  /**
   * <code>required string bucket = 1;</code>
   *
   * <pre>
   * Address of the S3 bucket
   * </pre>
   */
  public boolean hasBucket() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string bucket = 1;</code>
   *
   * <pre>
   * Address of the S3 bucket
   * </pre>
   */
  public java.lang.String getBucket() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        bucket_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string bucket = 1;</code>
   *
   * <pre>
   * Address of the S3 bucket
   * </pre>
   */
  public com.google.protobuf.ByteString
      getBucketBytes() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bucket_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private java.lang.Object version_;
  /**
   * <code>required string version = 2;</code>
   *
   * <pre>
   * Configuration version
   * </pre>
   */
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string version = 2;</code>
   *
   * <pre>
   * Configuration version
   * </pre>
   */
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        version_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string version = 2;</code>
   *
   * <pre>
   * Configuration version
   * </pre>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGES_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList images_;
  /**
   * <code>repeated string images = 3;</code>
   *
   * <pre>
   * Top level Paskoocheh images
   * </pre>
   */
  public com.google.protobuf.ProtocolStringList
      getImagesList() {
    return images_;
  }
  /**
   * <code>repeated string images = 3;</code>
   *
   * <pre>
   * Top level Paskoocheh images
   * </pre>
   */
  public int getImagesCount() {
    return images_.size();
  }
  /**
   * <code>repeated string images = 3;</code>
   *
   * <pre>
   * Top level Paskoocheh images
   * </pre>
   */
  public java.lang.String getImages(int index) {
    return images_.get(index);
  }
  /**
   * <code>repeated string images = 3;</code>
   *
   * <pre>
   * Top level Paskoocheh images
   * </pre>
   */
  public com.google.protobuf.ByteString
      getImagesBytes(int index) {
    return images_.getByteString(index);
  }

  public static final int PLATFORMS_FIELD_NUMBER = 4;
  private java.util.List<org.asl19.paskoocheh.Platform> platforms_;
  /**
   * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
   *
   * <pre>
   * Platform of the tool
   * </pre>
   */
  public java.util.List<org.asl19.paskoocheh.Platform> getPlatformsList() {
    return platforms_;
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
   *
   * <pre>
   * Platform of the tool
   * </pre>
   */
  public java.util.List<? extends org.asl19.paskoocheh.PlatformOrBuilder> 
      getPlatformsOrBuilderList() {
    return platforms_;
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
   *
   * <pre>
   * Platform of the tool
   * </pre>
   */
  public int getPlatformsCount() {
    return platforms_.size();
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
   *
   * <pre>
   * Platform of the tool
   * </pre>
   */
  public org.asl19.paskoocheh.Platform getPlatforms(int index) {
    return platforms_.get(index);
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
   *
   * <pre>
   * Platform of the tool
   * </pre>
   */
  public org.asl19.paskoocheh.PlatformOrBuilder getPlatformsOrBuilder(
      int index) {
    return platforms_.get(index);
  }

  public static final int UPDATE_FIELD_NUMBER = 20;
  private java.util.List<org.asl19.paskoocheh.Message> update_;
  /**
   * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
   *
   * <pre>
   * Update messages that are general for all users
   * </pre>
   */
  public java.util.List<org.asl19.paskoocheh.Message> getUpdateList() {
    return update_;
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
   *
   * <pre>
   * Update messages that are general for all users
   * </pre>
   */
  public java.util.List<? extends org.asl19.paskoocheh.MessageOrBuilder> 
      getUpdateOrBuilderList() {
    return update_;
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
   *
   * <pre>
   * Update messages that are general for all users
   * </pre>
   */
  public int getUpdateCount() {
    return update_.size();
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
   *
   * <pre>
   * Update messages that are general for all users
   * </pre>
   */
  public org.asl19.paskoocheh.Message getUpdate(int index) {
    return update_.get(index);
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
   *
   * <pre>
   * Update messages that are general for all users
   * </pre>
   */
  public org.asl19.paskoocheh.MessageOrBuilder getUpdateOrBuilder(
      int index) {
    return update_.get(index);
  }

  private void initFields() {
    bucket_ = "";
    version_ = "";
    images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    platforms_ = java.util.Collections.emptyList();
    update_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasBucket()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasVersion()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getPlatformsCount(); i++) {
      if (!getPlatforms(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getUpdateCount(); i++) {
      if (!getUpdate(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getBucketBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getVersionBytes());
    }
    for (int i = 0; i < images_.size(); i++) {
      output.writeBytes(3, images_.getByteString(i));
    }
    for (int i = 0; i < platforms_.size(); i++) {
      output.writeMessage(4, platforms_.get(i));
    }
    for (int i = 0; i < update_.size(); i++) {
      output.writeMessage(20, update_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getBucketBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getVersionBytes());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < images_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(images_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getImagesList().size();
    }
    for (int i = 0; i < platforms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, platforms_.get(i));
    }
    for (int i = 0; i < update_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, update_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.asl19.paskoocheh.Config)) {
      return super.equals(obj);
    }
    org.asl19.paskoocheh.Config other = (org.asl19.paskoocheh.Config) obj;

    boolean result = true;
    result = result && (hasBucket() == other.hasBucket());
    if (hasBucket()) {
      result = result && getBucket()
          .equals(other.getBucket());
    }
    result = result && (hasVersion() == other.hasVersion());
    if (hasVersion()) {
      result = result && getVersion()
          .equals(other.getVersion());
    }
    result = result && getImagesList()
        .equals(other.getImagesList());
    result = result && getPlatformsList()
        .equals(other.getPlatformsList());
    result = result && getUpdateList()
        .equals(other.getUpdateList());
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasBucket()) {
      hash = (37 * hash) + BUCKET_FIELD_NUMBER;
      hash = (53 * hash) + getBucket().hashCode();
    }
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    if (getImagesCount() > 0) {
      hash = (37 * hash) + IMAGES_FIELD_NUMBER;
      hash = (53 * hash) + getImagesList().hashCode();
    }
    if (getPlatformsCount() > 0) {
      hash = (37 * hash) + PLATFORMS_FIELD_NUMBER;
      hash = (53 * hash) + getPlatformsList().hashCode();
    }
    if (getUpdateCount() > 0) {
      hash = (37 * hash) + UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.asl19.paskoocheh.Config parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.asl19.paskoocheh.Config parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Config parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.asl19.paskoocheh.Config parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Config parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.asl19.paskoocheh.Config parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Config parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.asl19.paskoocheh.Config parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Config parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.asl19.paskoocheh.Config parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.asl19.paskoocheh.Config prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.asl19.paskoocheh.Config}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.asl19.paskoocheh.Config)
      org.asl19.paskoocheh.ConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Config_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.asl19.paskoocheh.Config.class, org.asl19.paskoocheh.Config.Builder.class);
    }

    // Construct using org.asl19.paskoocheh.Config.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getPlatformsFieldBuilder();
        getUpdateFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      bucket_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (platformsBuilder_ == null) {
        platforms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        platformsBuilder_.clear();
      }
      if (updateBuilder_ == null) {
        update_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        updateBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Config_descriptor;
    }

    public org.asl19.paskoocheh.Config getDefaultInstanceForType() {
      return org.asl19.paskoocheh.Config.getDefaultInstance();
    }

    public org.asl19.paskoocheh.Config build() {
      org.asl19.paskoocheh.Config result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.asl19.paskoocheh.Config buildPartial() {
      org.asl19.paskoocheh.Config result = new org.asl19.paskoocheh.Config(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.bucket_ = bucket_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.version_ = version_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        images_ = images_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.images_ = images_;
      if (platformsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          platforms_ = java.util.Collections.unmodifiableList(platforms_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.platforms_ = platforms_;
      } else {
        result.platforms_ = platformsBuilder_.build();
      }
      if (updateBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          update_ = java.util.Collections.unmodifiableList(update_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.update_ = update_;
      } else {
        result.update_ = updateBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.asl19.paskoocheh.Config) {
        return mergeFrom((org.asl19.paskoocheh.Config)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.asl19.paskoocheh.Config other) {
      if (other == org.asl19.paskoocheh.Config.getDefaultInstance()) return this;
      if (other.hasBucket()) {
        bitField0_ |= 0x00000001;
        bucket_ = other.bucket_;
        onChanged();
      }
      if (other.hasVersion()) {
        bitField0_ |= 0x00000002;
        version_ = other.version_;
        onChanged();
      }
      if (!other.images_.isEmpty()) {
        if (images_.isEmpty()) {
          images_ = other.images_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureImagesIsMutable();
          images_.addAll(other.images_);
        }
        onChanged();
      }
      if (platformsBuilder_ == null) {
        if (!other.platforms_.isEmpty()) {
          if (platforms_.isEmpty()) {
            platforms_ = other.platforms_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePlatformsIsMutable();
            platforms_.addAll(other.platforms_);
          }
          onChanged();
        }
      } else {
        if (!other.platforms_.isEmpty()) {
          if (platformsBuilder_.isEmpty()) {
            platformsBuilder_.dispose();
            platformsBuilder_ = null;
            platforms_ = other.platforms_;
            bitField0_ = (bitField0_ & ~0x00000008);
            platformsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPlatformsFieldBuilder() : null;
          } else {
            platformsBuilder_.addAllMessages(other.platforms_);
          }
        }
      }
      if (updateBuilder_ == null) {
        if (!other.update_.isEmpty()) {
          if (update_.isEmpty()) {
            update_ = other.update_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureUpdateIsMutable();
            update_.addAll(other.update_);
          }
          onChanged();
        }
      } else {
        if (!other.update_.isEmpty()) {
          if (updateBuilder_.isEmpty()) {
            updateBuilder_.dispose();
            updateBuilder_ = null;
            update_ = other.update_;
            bitField0_ = (bitField0_ & ~0x00000010);
            updateBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getUpdateFieldBuilder() : null;
          } else {
            updateBuilder_.addAllMessages(other.update_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasBucket()) {
        
        return false;
      }
      if (!hasVersion()) {
        
        return false;
      }
      for (int i = 0; i < getPlatformsCount(); i++) {
        if (!getPlatforms(i).isInitialized()) {
          
          return false;
        }
      }
      for (int i = 0; i < getUpdateCount(); i++) {
        if (!getUpdate(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.asl19.paskoocheh.Config parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.asl19.paskoocheh.Config) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object bucket_ = "";
    /**
     * <code>required string bucket = 1;</code>
     *
     * <pre>
     * Address of the S3 bucket
     * </pre>
     */
    public boolean hasBucket() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string bucket = 1;</code>
     *
     * <pre>
     * Address of the S3 bucket
     * </pre>
     */
    public java.lang.String getBucket() {
      java.lang.Object ref = bucket_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bucket_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string bucket = 1;</code>
     *
     * <pre>
     * Address of the S3 bucket
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBucketBytes() {
      java.lang.Object ref = bucket_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bucket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string bucket = 1;</code>
     *
     * <pre>
     * Address of the S3 bucket
     * </pre>
     */
    public Builder setBucket(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      bucket_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string bucket = 1;</code>
     *
     * <pre>
     * Address of the S3 bucket
     * </pre>
     */
    public Builder clearBucket() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bucket_ = getDefaultInstance().getBucket();
      onChanged();
      return this;
    }
    /**
     * <code>required string bucket = 1;</code>
     *
     * <pre>
     * Address of the S3 bucket
     * </pre>
     */
    public Builder setBucketBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      bucket_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>required string version = 2;</code>
     *
     * <pre>
     * Configuration version
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string version = 2;</code>
     *
     * <pre>
     * Configuration version
     * </pre>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string version = 2;</code>
     *
     * <pre>
     * Configuration version
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string version = 2;</code>
     *
     * <pre>
     * Configuration version
     * </pre>
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string version = 2;</code>
     *
     * <pre>
     * Configuration version
     * </pre>
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000002);
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>required string version = 2;</code>
     *
     * <pre>
     * Configuration version
     * </pre>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      version_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureImagesIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        images_ = new com.google.protobuf.LazyStringArrayList(images_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string images = 3;</code>
     *
     * <pre>
     * Top level Paskoocheh images
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getImagesList() {
      return images_.getUnmodifiableView();
    }
    /**
     * <code>repeated string images = 3;</code>
     *
     * <pre>
     * Top level Paskoocheh images
     * </pre>
     */
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <code>repeated string images = 3;</code>
     *
     * <pre>
     * Top level Paskoocheh images
     * </pre>
     */
    public java.lang.String getImages(int index) {
      return images_.get(index);
    }
    /**
     * <code>repeated string images = 3;</code>
     *
     * <pre>
     * Top level Paskoocheh images
     * </pre>
     */
    public com.google.protobuf.ByteString
        getImagesBytes(int index) {
      return images_.getByteString(index);
    }
    /**
     * <code>repeated string images = 3;</code>
     *
     * <pre>
     * Top level Paskoocheh images
     * </pre>
     */
    public Builder setImages(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
      images_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string images = 3;</code>
     *
     * <pre>
     * Top level Paskoocheh images
     * </pre>
     */
    public Builder addImages(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
      images_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string images = 3;</code>
     *
     * <pre>
     * Top level Paskoocheh images
     * </pre>
     */
    public Builder addAllImages(
        java.lang.Iterable<java.lang.String> values) {
      ensureImagesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, images_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string images = 3;</code>
     *
     * <pre>
     * Top level Paskoocheh images
     * </pre>
     */
    public Builder clearImages() {
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string images = 3;</code>
     *
     * <pre>
     * Top level Paskoocheh images
     * </pre>
     */
    public Builder addImagesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
      images_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<org.asl19.paskoocheh.Platform> platforms_ =
      java.util.Collections.emptyList();
    private void ensurePlatformsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        platforms_ = new java.util.ArrayList<org.asl19.paskoocheh.Platform>(platforms_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.asl19.paskoocheh.Platform, org.asl19.paskoocheh.Platform.Builder, org.asl19.paskoocheh.PlatformOrBuilder> platformsBuilder_;

    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public java.util.List<org.asl19.paskoocheh.Platform> getPlatformsList() {
      if (platformsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(platforms_);
      } else {
        return platformsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public int getPlatformsCount() {
      if (platformsBuilder_ == null) {
        return platforms_.size();
      } else {
        return platformsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public org.asl19.paskoocheh.Platform getPlatforms(int index) {
      if (platformsBuilder_ == null) {
        return platforms_.get(index);
      } else {
        return platformsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public Builder setPlatforms(
        int index, org.asl19.paskoocheh.Platform value) {
      if (platformsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlatformsIsMutable();
        platforms_.set(index, value);
        onChanged();
      } else {
        platformsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public Builder setPlatforms(
        int index, org.asl19.paskoocheh.Platform.Builder builderForValue) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.set(index, builderForValue.build());
        onChanged();
      } else {
        platformsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public Builder addPlatforms(org.asl19.paskoocheh.Platform value) {
      if (platformsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlatformsIsMutable();
        platforms_.add(value);
        onChanged();
      } else {
        platformsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public Builder addPlatforms(
        int index, org.asl19.paskoocheh.Platform value) {
      if (platformsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlatformsIsMutable();
        platforms_.add(index, value);
        onChanged();
      } else {
        platformsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public Builder addPlatforms(
        org.asl19.paskoocheh.Platform.Builder builderForValue) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.add(builderForValue.build());
        onChanged();
      } else {
        platformsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public Builder addPlatforms(
        int index, org.asl19.paskoocheh.Platform.Builder builderForValue) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.add(index, builderForValue.build());
        onChanged();
      } else {
        platformsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public Builder addAllPlatforms(
        java.lang.Iterable<? extends org.asl19.paskoocheh.Platform> values) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, platforms_);
        onChanged();
      } else {
        platformsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public Builder clearPlatforms() {
      if (platformsBuilder_ == null) {
        platforms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        platformsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public Builder removePlatforms(int index) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.remove(index);
        onChanged();
      } else {
        platformsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public org.asl19.paskoocheh.Platform.Builder getPlatformsBuilder(
        int index) {
      return getPlatformsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public org.asl19.paskoocheh.PlatformOrBuilder getPlatformsOrBuilder(
        int index) {
      if (platformsBuilder_ == null) {
        return platforms_.get(index);  } else {
        return platformsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public java.util.List<? extends org.asl19.paskoocheh.PlatformOrBuilder> 
         getPlatformsOrBuilderList() {
      if (platformsBuilder_ != null) {
        return platformsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(platforms_);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public org.asl19.paskoocheh.Platform.Builder addPlatformsBuilder() {
      return getPlatformsFieldBuilder().addBuilder(
          org.asl19.paskoocheh.Platform.getDefaultInstance());
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public org.asl19.paskoocheh.Platform.Builder addPlatformsBuilder(
        int index) {
      return getPlatformsFieldBuilder().addBuilder(
          index, org.asl19.paskoocheh.Platform.getDefaultInstance());
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Platform platforms = 4;</code>
     *
     * <pre>
     * Platform of the tool
     * </pre>
     */
    public java.util.List<org.asl19.paskoocheh.Platform.Builder> 
         getPlatformsBuilderList() {
      return getPlatformsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.asl19.paskoocheh.Platform, org.asl19.paskoocheh.Platform.Builder, org.asl19.paskoocheh.PlatformOrBuilder> 
        getPlatformsFieldBuilder() {
      if (platformsBuilder_ == null) {
        platformsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.asl19.paskoocheh.Platform, org.asl19.paskoocheh.Platform.Builder, org.asl19.paskoocheh.PlatformOrBuilder>(
                platforms_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        platforms_ = null;
      }
      return platformsBuilder_;
    }

    private java.util.List<org.asl19.paskoocheh.Message> update_ =
      java.util.Collections.emptyList();
    private void ensureUpdateIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        update_ = new java.util.ArrayList<org.asl19.paskoocheh.Message>(update_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.asl19.paskoocheh.Message, org.asl19.paskoocheh.Message.Builder, org.asl19.paskoocheh.MessageOrBuilder> updateBuilder_;

    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public java.util.List<org.asl19.paskoocheh.Message> getUpdateList() {
      if (updateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(update_);
      } else {
        return updateBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public int getUpdateCount() {
      if (updateBuilder_ == null) {
        return update_.size();
      } else {
        return updateBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public org.asl19.paskoocheh.Message getUpdate(int index) {
      if (updateBuilder_ == null) {
        return update_.get(index);
      } else {
        return updateBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public Builder setUpdate(
        int index, org.asl19.paskoocheh.Message value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.set(index, value);
        onChanged();
      } else {
        updateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public Builder setUpdate(
        int index, org.asl19.paskoocheh.Message.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.set(index, builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public Builder addUpdate(org.asl19.paskoocheh.Message value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.add(value);
        onChanged();
      } else {
        updateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public Builder addUpdate(
        int index, org.asl19.paskoocheh.Message value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.add(index, value);
        onChanged();
      } else {
        updateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public Builder addUpdate(
        org.asl19.paskoocheh.Message.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.add(builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public Builder addUpdate(
        int index, org.asl19.paskoocheh.Message.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.add(index, builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public Builder addAllUpdate(
        java.lang.Iterable<? extends org.asl19.paskoocheh.Message> values) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, update_);
        onChanged();
      } else {
        updateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public Builder clearUpdate() {
      if (updateBuilder_ == null) {
        update_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        updateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public Builder removeUpdate(int index) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.remove(index);
        onChanged();
      } else {
        updateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public org.asl19.paskoocheh.Message.Builder getUpdateBuilder(
        int index) {
      return getUpdateFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public org.asl19.paskoocheh.MessageOrBuilder getUpdateOrBuilder(
        int index) {
      if (updateBuilder_ == null) {
        return update_.get(index);  } else {
        return updateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public java.util.List<? extends org.asl19.paskoocheh.MessageOrBuilder> 
         getUpdateOrBuilderList() {
      if (updateBuilder_ != null) {
        return updateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(update_);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public org.asl19.paskoocheh.Message.Builder addUpdateBuilder() {
      return getUpdateFieldBuilder().addBuilder(
          org.asl19.paskoocheh.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public org.asl19.paskoocheh.Message.Builder addUpdateBuilder(
        int index) {
      return getUpdateFieldBuilder().addBuilder(
          index, org.asl19.paskoocheh.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Update messages that are general for all users
     * </pre>
     */
    public java.util.List<org.asl19.paskoocheh.Message.Builder> 
         getUpdateBuilderList() {
      return getUpdateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.asl19.paskoocheh.Message, org.asl19.paskoocheh.Message.Builder, org.asl19.paskoocheh.MessageOrBuilder> 
        getUpdateFieldBuilder() {
      if (updateBuilder_ == null) {
        updateBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.asl19.paskoocheh.Message, org.asl19.paskoocheh.Message.Builder, org.asl19.paskoocheh.MessageOrBuilder>(
                update_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        update_ = null;
      }
      return updateBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.asl19.paskoocheh.Config)
  }

  static {
    defaultInstance = new Config(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.asl19.paskoocheh.Config)
}

