// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paskoocheh.proto

package org.asl19.paskoocheh;

/**
 * Protobuf type {@code org.asl19.paskoocheh.Contact}
 *
 * <pre>
 * A message to hold info for an online Entity
 * Used for tool author and tool vendor
 * </pre>
 */
public final class Contact extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.asl19.paskoocheh.Contact)
    ContactOrBuilder {
  // Use Contact.newBuilder() to construct.
  private Contact(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Contact(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Contact defaultInstance;
  public static Contact getDefaultInstance() {
    return defaultInstance;
  }

  public Contact getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Contact(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            name_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            websiteUrl_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            userSupportUrl_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            supportEmail_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            blogUrl_ = bs;
            break;
          }
          case 50: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000020;
            facebookUrl_ = bs;
            break;
          }
          case 58: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000040;
            twitterHandle_ = bs;
            break;
          }
          case 66: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000080;
            feedUrl_ = bs;
            break;
          }
          case 74: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000100;
            mailResponderEmail_ = bs;
            break;
          }
          case 82: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000200;
            sourceUrl_ = bs;
            break;
          }
          case 90: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000400;
            description_ = bs;
            break;
          }
          case 98: {
            if (!((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
              translation_ = new java.util.ArrayList<org.asl19.paskoocheh.Translation>();
              mutable_bitField0_ |= 0x00000800;
            }
            translation_.add(input.readMessage(org.asl19.paskoocheh.Translation.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
        translation_ = java.util.Collections.unmodifiableList(translation_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Contact_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Contact_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.asl19.paskoocheh.Contact.class, org.asl19.paskoocheh.Contact.Builder.class);
  }

  public static com.google.protobuf.Parser<Contact> PARSER =
      new com.google.protobuf.AbstractParser<Contact>() {
    public Contact parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Contact(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Contact> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.Object name_;
  /**
   * <code>required string name = 1;</code>
   *
   * <pre>
   * Name of the entity
   * </pre>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string name = 1;</code>
   *
   * <pre>
   * Name of the entity
   * </pre>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 1;</code>
   *
   * <pre>
   * Name of the entity
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEBSITE_URL_FIELD_NUMBER = 2;
  private java.lang.Object websiteUrl_;
  /**
   * <code>optional string website_url = 2;</code>
   *
   * <pre>
   * Website URL
   * </pre>
   */
  public boolean hasWebsiteUrl() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string website_url = 2;</code>
   *
   * <pre>
   * Website URL
   * </pre>
   */
  public java.lang.String getWebsiteUrl() {
    java.lang.Object ref = websiteUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        websiteUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string website_url = 2;</code>
   *
   * <pre>
   * Website URL
   * </pre>
   */
  public com.google.protobuf.ByteString
      getWebsiteUrlBytes() {
    java.lang.Object ref = websiteUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      websiteUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_SUPPORT_URL_FIELD_NUMBER = 3;
  private java.lang.Object userSupportUrl_;
  /**
   * <code>optional string user_support_url = 3;</code>
   *
   * <pre>
   * URL for user support
   * </pre>
   */
  public boolean hasUserSupportUrl() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string user_support_url = 3;</code>
   *
   * <pre>
   * URL for user support
   * </pre>
   */
  public java.lang.String getUserSupportUrl() {
    java.lang.Object ref = userSupportUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userSupportUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string user_support_url = 3;</code>
   *
   * <pre>
   * URL for user support
   * </pre>
   */
  public com.google.protobuf.ByteString
      getUserSupportUrlBytes() {
    java.lang.Object ref = userSupportUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userSupportUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUPPORT_EMAIL_FIELD_NUMBER = 4;
  private java.lang.Object supportEmail_;
  /**
   * <code>optional string support_email = 4;</code>
   *
   * <pre>
   * Email for user support
   * </pre>
   */
  public boolean hasSupportEmail() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string support_email = 4;</code>
   *
   * <pre>
   * Email for user support
   * </pre>
   */
  public java.lang.String getSupportEmail() {
    java.lang.Object ref = supportEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        supportEmail_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string support_email = 4;</code>
   *
   * <pre>
   * Email for user support
   * </pre>
   */
  public com.google.protobuf.ByteString
      getSupportEmailBytes() {
    java.lang.Object ref = supportEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      supportEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLOG_URL_FIELD_NUMBER = 5;
  private java.lang.Object blogUrl_;
  /**
   * <code>optional string blog_url = 5;</code>
   *
   * <pre>
   * Blog URL
   * </pre>
   */
  public boolean hasBlogUrl() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string blog_url = 5;</code>
   *
   * <pre>
   * Blog URL
   * </pre>
   */
  public java.lang.String getBlogUrl() {
    java.lang.Object ref = blogUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        blogUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string blog_url = 5;</code>
   *
   * <pre>
   * Blog URL
   * </pre>
   */
  public com.google.protobuf.ByteString
      getBlogUrlBytes() {
    java.lang.Object ref = blogUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      blogUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FACEBOOK_URL_FIELD_NUMBER = 6;
  private java.lang.Object facebookUrl_;
  /**
   * <code>optional string facebook_url = 6;</code>
   *
   * <pre>
   * Facebook page URL
   * </pre>
   */
  public boolean hasFacebookUrl() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string facebook_url = 6;</code>
   *
   * <pre>
   * Facebook page URL
   * </pre>
   */
  public java.lang.String getFacebookUrl() {
    java.lang.Object ref = facebookUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        facebookUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string facebook_url = 6;</code>
   *
   * <pre>
   * Facebook page URL
   * </pre>
   */
  public com.google.protobuf.ByteString
      getFacebookUrlBytes() {
    java.lang.Object ref = facebookUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      facebookUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TWITTER_HANDLE_FIELD_NUMBER = 7;
  private java.lang.Object twitterHandle_;
  /**
   * <code>optional string twitter_handle = 7;</code>
   *
   * <pre>
   * Twitter URL
   * </pre>
   */
  public boolean hasTwitterHandle() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional string twitter_handle = 7;</code>
   *
   * <pre>
   * Twitter URL
   * </pre>
   */
  public java.lang.String getTwitterHandle() {
    java.lang.Object ref = twitterHandle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        twitterHandle_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string twitter_handle = 7;</code>
   *
   * <pre>
   * Twitter URL
   * </pre>
   */
  public com.google.protobuf.ByteString
      getTwitterHandleBytes() {
    java.lang.Object ref = twitterHandle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      twitterHandle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FEED_URL_FIELD_NUMBER = 8;
  private java.lang.Object feedUrl_;
  /**
   * <code>optional string feed_url = 8;</code>
   *
   * <pre>
   * RSS Feed
   * </pre>
   */
  public boolean hasFeedUrl() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional string feed_url = 8;</code>
   *
   * <pre>
   * RSS Feed
   * </pre>
   */
  public java.lang.String getFeedUrl() {
    java.lang.Object ref = feedUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        feedUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string feed_url = 8;</code>
   *
   * <pre>
   * RSS Feed
   * </pre>
   */
  public com.google.protobuf.ByteString
      getFeedUrlBytes() {
    java.lang.Object ref = feedUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      feedUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAIL_RESPONDER_EMAIL_FIELD_NUMBER = 9;
  private java.lang.Object mailResponderEmail_;
  /**
   * <code>optional string mail_responder_email = 9;</code>
   *
   * <pre>
   * Email Address for tool delivery
   * </pre>
   */
  public boolean hasMailResponderEmail() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string mail_responder_email = 9;</code>
   *
   * <pre>
   * Email Address for tool delivery
   * </pre>
   */
  public java.lang.String getMailResponderEmail() {
    java.lang.Object ref = mailResponderEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        mailResponderEmail_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string mail_responder_email = 9;</code>
   *
   * <pre>
   * Email Address for tool delivery
   * </pre>
   */
  public com.google.protobuf.ByteString
      getMailResponderEmailBytes() {
    java.lang.Object ref = mailResponderEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mailResponderEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_URL_FIELD_NUMBER = 10;
  private java.lang.Object sourceUrl_;
  /**
   * <code>optional string source_url = 10;</code>
   *
   * <pre>
   * URL of the open source repo
   * </pre>
   */
  public boolean hasSourceUrl() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional string source_url = 10;</code>
   *
   * <pre>
   * URL of the open source repo
   * </pre>
   */
  public java.lang.String getSourceUrl() {
    java.lang.Object ref = sourceUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sourceUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string source_url = 10;</code>
   *
   * <pre>
   * URL of the open source repo
   * </pre>
   */
  public com.google.protobuf.ByteString
      getSourceUrlBytes() {
    java.lang.Object ref = sourceUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 11;
  private java.lang.Object description_;
  /**
   * <code>optional string description = 11;</code>
   *
   * <pre>
   * Description text for the entity
   * </pre>
   */
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  /**
   * <code>optional string description = 11;</code>
   *
   * <pre>
   * Description text for the entity
   * </pre>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        description_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string description = 11;</code>
   *
   * <pre>
   * Description text for the entity
   * </pre>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSLATION_FIELD_NUMBER = 12;
  private java.util.List<org.asl19.paskoocheh.Translation> translation_;
  /**
   * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
   *
   * <pre>
   * Language specific information
   * </pre>
   */
  public java.util.List<org.asl19.paskoocheh.Translation> getTranslationList() {
    return translation_;
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
   *
   * <pre>
   * Language specific information
   * </pre>
   */
  public java.util.List<? extends org.asl19.paskoocheh.TranslationOrBuilder> 
      getTranslationOrBuilderList() {
    return translation_;
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
   *
   * <pre>
   * Language specific information
   * </pre>
   */
  public int getTranslationCount() {
    return translation_.size();
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
   *
   * <pre>
   * Language specific information
   * </pre>
   */
  public org.asl19.paskoocheh.Translation getTranslation(int index) {
    return translation_.get(index);
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
   *
   * <pre>
   * Language specific information
   * </pre>
   */
  public org.asl19.paskoocheh.TranslationOrBuilder getTranslationOrBuilder(
      int index) {
    return translation_.get(index);
  }

  private void initFields() {
    name_ = "";
    websiteUrl_ = "";
    userSupportUrl_ = "";
    supportEmail_ = "";
    blogUrl_ = "";
    facebookUrl_ = "";
    twitterHandle_ = "";
    feedUrl_ = "";
    mailResponderEmail_ = "";
    sourceUrl_ = "";
    description_ = "";
    translation_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getTranslationCount(); i++) {
      if (!getTranslation(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getWebsiteUrlBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getUserSupportUrlBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getSupportEmailBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getBlogUrlBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBytes(6, getFacebookUrlBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeBytes(7, getTwitterHandleBytes());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeBytes(8, getFeedUrlBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeBytes(9, getMailResponderEmailBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeBytes(10, getSourceUrlBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeBytes(11, getDescriptionBytes());
    }
    for (int i = 0; i < translation_.size(); i++) {
      output.writeMessage(12, translation_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getWebsiteUrlBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getUserSupportUrlBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getSupportEmailBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getBlogUrlBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, getFacebookUrlBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, getTwitterHandleBytes());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, getFeedUrlBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, getMailResponderEmailBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, getSourceUrlBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(11, getDescriptionBytes());
    }
    for (int i = 0; i < translation_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, translation_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.asl19.paskoocheh.Contact)) {
      return super.equals(obj);
    }
    org.asl19.paskoocheh.Contact other = (org.asl19.paskoocheh.Contact) obj;

    boolean result = true;
    result = result && (hasName() == other.hasName());
    if (hasName()) {
      result = result && getName()
          .equals(other.getName());
    }
    result = result && (hasWebsiteUrl() == other.hasWebsiteUrl());
    if (hasWebsiteUrl()) {
      result = result && getWebsiteUrl()
          .equals(other.getWebsiteUrl());
    }
    result = result && (hasUserSupportUrl() == other.hasUserSupportUrl());
    if (hasUserSupportUrl()) {
      result = result && getUserSupportUrl()
          .equals(other.getUserSupportUrl());
    }
    result = result && (hasSupportEmail() == other.hasSupportEmail());
    if (hasSupportEmail()) {
      result = result && getSupportEmail()
          .equals(other.getSupportEmail());
    }
    result = result && (hasBlogUrl() == other.hasBlogUrl());
    if (hasBlogUrl()) {
      result = result && getBlogUrl()
          .equals(other.getBlogUrl());
    }
    result = result && (hasFacebookUrl() == other.hasFacebookUrl());
    if (hasFacebookUrl()) {
      result = result && getFacebookUrl()
          .equals(other.getFacebookUrl());
    }
    result = result && (hasTwitterHandle() == other.hasTwitterHandle());
    if (hasTwitterHandle()) {
      result = result && getTwitterHandle()
          .equals(other.getTwitterHandle());
    }
    result = result && (hasFeedUrl() == other.hasFeedUrl());
    if (hasFeedUrl()) {
      result = result && getFeedUrl()
          .equals(other.getFeedUrl());
    }
    result = result && (hasMailResponderEmail() == other.hasMailResponderEmail());
    if (hasMailResponderEmail()) {
      result = result && getMailResponderEmail()
          .equals(other.getMailResponderEmail());
    }
    result = result && (hasSourceUrl() == other.hasSourceUrl());
    if (hasSourceUrl()) {
      result = result && getSourceUrl()
          .equals(other.getSourceUrl());
    }
    result = result && (hasDescription() == other.hasDescription());
    if (hasDescription()) {
      result = result && getDescription()
          .equals(other.getDescription());
    }
    result = result && getTranslationList()
        .equals(other.getTranslationList());
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasWebsiteUrl()) {
      hash = (37 * hash) + WEBSITE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getWebsiteUrl().hashCode();
    }
    if (hasUserSupportUrl()) {
      hash = (37 * hash) + USER_SUPPORT_URL_FIELD_NUMBER;
      hash = (53 * hash) + getUserSupportUrl().hashCode();
    }
    if (hasSupportEmail()) {
      hash = (37 * hash) + SUPPORT_EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getSupportEmail().hashCode();
    }
    if (hasBlogUrl()) {
      hash = (37 * hash) + BLOG_URL_FIELD_NUMBER;
      hash = (53 * hash) + getBlogUrl().hashCode();
    }
    if (hasFacebookUrl()) {
      hash = (37 * hash) + FACEBOOK_URL_FIELD_NUMBER;
      hash = (53 * hash) + getFacebookUrl().hashCode();
    }
    if (hasTwitterHandle()) {
      hash = (37 * hash) + TWITTER_HANDLE_FIELD_NUMBER;
      hash = (53 * hash) + getTwitterHandle().hashCode();
    }
    if (hasFeedUrl()) {
      hash = (37 * hash) + FEED_URL_FIELD_NUMBER;
      hash = (53 * hash) + getFeedUrl().hashCode();
    }
    if (hasMailResponderEmail()) {
      hash = (37 * hash) + MAIL_RESPONDER_EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getMailResponderEmail().hashCode();
    }
    if (hasSourceUrl()) {
      hash = (37 * hash) + SOURCE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getSourceUrl().hashCode();
    }
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    if (getTranslationCount() > 0) {
      hash = (37 * hash) + TRANSLATION_FIELD_NUMBER;
      hash = (53 * hash) + getTranslationList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.asl19.paskoocheh.Contact parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.asl19.paskoocheh.Contact parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Contact parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.asl19.paskoocheh.Contact parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Contact parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.asl19.paskoocheh.Contact parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Contact parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.asl19.paskoocheh.Contact parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Contact parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.asl19.paskoocheh.Contact parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.asl19.paskoocheh.Contact prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.asl19.paskoocheh.Contact}
   *
   * <pre>
   * A message to hold info for an online Entity
   * Used for tool author and tool vendor
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.asl19.paskoocheh.Contact)
      org.asl19.paskoocheh.ContactOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Contact_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Contact_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.asl19.paskoocheh.Contact.class, org.asl19.paskoocheh.Contact.Builder.class);
    }

    // Construct using org.asl19.paskoocheh.Contact.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getTranslationFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      websiteUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      userSupportUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      supportEmail_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      blogUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      facebookUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      twitterHandle_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      feedUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      mailResponderEmail_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      sourceUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000200);
      description_ = "";
      bitField0_ = (bitField0_ & ~0x00000400);
      if (translationBuilder_ == null) {
        translation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
      } else {
        translationBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Contact_descriptor;
    }

    public org.asl19.paskoocheh.Contact getDefaultInstanceForType() {
      return org.asl19.paskoocheh.Contact.getDefaultInstance();
    }

    public org.asl19.paskoocheh.Contact build() {
      org.asl19.paskoocheh.Contact result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.asl19.paskoocheh.Contact buildPartial() {
      org.asl19.paskoocheh.Contact result = new org.asl19.paskoocheh.Contact(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.websiteUrl_ = websiteUrl_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.userSupportUrl_ = userSupportUrl_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.supportEmail_ = supportEmail_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.blogUrl_ = blogUrl_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.facebookUrl_ = facebookUrl_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.twitterHandle_ = twitterHandle_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.feedUrl_ = feedUrl_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.mailResponderEmail_ = mailResponderEmail_;
      if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
        to_bitField0_ |= 0x00000200;
      }
      result.sourceUrl_ = sourceUrl_;
      if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
        to_bitField0_ |= 0x00000400;
      }
      result.description_ = description_;
      if (translationBuilder_ == null) {
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          translation_ = java.util.Collections.unmodifiableList(translation_);
          bitField0_ = (bitField0_ & ~0x00000800);
        }
        result.translation_ = translation_;
      } else {
        result.translation_ = translationBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.asl19.paskoocheh.Contact) {
        return mergeFrom((org.asl19.paskoocheh.Contact)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.asl19.paskoocheh.Contact other) {
      if (other == org.asl19.paskoocheh.Contact.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasWebsiteUrl()) {
        bitField0_ |= 0x00000002;
        websiteUrl_ = other.websiteUrl_;
        onChanged();
      }
      if (other.hasUserSupportUrl()) {
        bitField0_ |= 0x00000004;
        userSupportUrl_ = other.userSupportUrl_;
        onChanged();
      }
      if (other.hasSupportEmail()) {
        bitField0_ |= 0x00000008;
        supportEmail_ = other.supportEmail_;
        onChanged();
      }
      if (other.hasBlogUrl()) {
        bitField0_ |= 0x00000010;
        blogUrl_ = other.blogUrl_;
        onChanged();
      }
      if (other.hasFacebookUrl()) {
        bitField0_ |= 0x00000020;
        facebookUrl_ = other.facebookUrl_;
        onChanged();
      }
      if (other.hasTwitterHandle()) {
        bitField0_ |= 0x00000040;
        twitterHandle_ = other.twitterHandle_;
        onChanged();
      }
      if (other.hasFeedUrl()) {
        bitField0_ |= 0x00000080;
        feedUrl_ = other.feedUrl_;
        onChanged();
      }
      if (other.hasMailResponderEmail()) {
        bitField0_ |= 0x00000100;
        mailResponderEmail_ = other.mailResponderEmail_;
        onChanged();
      }
      if (other.hasSourceUrl()) {
        bitField0_ |= 0x00000200;
        sourceUrl_ = other.sourceUrl_;
        onChanged();
      }
      if (other.hasDescription()) {
        bitField0_ |= 0x00000400;
        description_ = other.description_;
        onChanged();
      }
      if (translationBuilder_ == null) {
        if (!other.translation_.isEmpty()) {
          if (translation_.isEmpty()) {
            translation_ = other.translation_;
            bitField0_ = (bitField0_ & ~0x00000800);
          } else {
            ensureTranslationIsMutable();
            translation_.addAll(other.translation_);
          }
          onChanged();
        }
      } else {
        if (!other.translation_.isEmpty()) {
          if (translationBuilder_.isEmpty()) {
            translationBuilder_.dispose();
            translationBuilder_ = null;
            translation_ = other.translation_;
            bitField0_ = (bitField0_ & ~0x00000800);
            translationBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTranslationFieldBuilder() : null;
          } else {
            translationBuilder_.addAllMessages(other.translation_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasName()) {
        
        return false;
      }
      for (int i = 0; i < getTranslationCount(); i++) {
        if (!getTranslation(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.asl19.paskoocheh.Contact parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.asl19.paskoocheh.Contact) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Name of the entity
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Name of the entity
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Name of the entity
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Name of the entity
     * </pre>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Name of the entity
     * </pre>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Name of the entity
     * </pre>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object websiteUrl_ = "";
    /**
     * <code>optional string website_url = 2;</code>
     *
     * <pre>
     * Website URL
     * </pre>
     */
    public boolean hasWebsiteUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string website_url = 2;</code>
     *
     * <pre>
     * Website URL
     * </pre>
     */
    public java.lang.String getWebsiteUrl() {
      java.lang.Object ref = websiteUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          websiteUrl_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string website_url = 2;</code>
     *
     * <pre>
     * Website URL
     * </pre>
     */
    public com.google.protobuf.ByteString
        getWebsiteUrlBytes() {
      java.lang.Object ref = websiteUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        websiteUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string website_url = 2;</code>
     *
     * <pre>
     * Website URL
     * </pre>
     */
    public Builder setWebsiteUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      websiteUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string website_url = 2;</code>
     *
     * <pre>
     * Website URL
     * </pre>
     */
    public Builder clearWebsiteUrl() {
      bitField0_ = (bitField0_ & ~0x00000002);
      websiteUrl_ = getDefaultInstance().getWebsiteUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string website_url = 2;</code>
     *
     * <pre>
     * Website URL
     * </pre>
     */
    public Builder setWebsiteUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      websiteUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userSupportUrl_ = "";
    /**
     * <code>optional string user_support_url = 3;</code>
     *
     * <pre>
     * URL for user support
     * </pre>
     */
    public boolean hasUserSupportUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string user_support_url = 3;</code>
     *
     * <pre>
     * URL for user support
     * </pre>
     */
    public java.lang.String getUserSupportUrl() {
      java.lang.Object ref = userSupportUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userSupportUrl_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string user_support_url = 3;</code>
     *
     * <pre>
     * URL for user support
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserSupportUrlBytes() {
      java.lang.Object ref = userSupportUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userSupportUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string user_support_url = 3;</code>
     *
     * <pre>
     * URL for user support
     * </pre>
     */
    public Builder setUserSupportUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      userSupportUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_support_url = 3;</code>
     *
     * <pre>
     * URL for user support
     * </pre>
     */
    public Builder clearUserSupportUrl() {
      bitField0_ = (bitField0_ & ~0x00000004);
      userSupportUrl_ = getDefaultInstance().getUserSupportUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_support_url = 3;</code>
     *
     * <pre>
     * URL for user support
     * </pre>
     */
    public Builder setUserSupportUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      userSupportUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object supportEmail_ = "";
    /**
     * <code>optional string support_email = 4;</code>
     *
     * <pre>
     * Email for user support
     * </pre>
     */
    public boolean hasSupportEmail() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string support_email = 4;</code>
     *
     * <pre>
     * Email for user support
     * </pre>
     */
    public java.lang.String getSupportEmail() {
      java.lang.Object ref = supportEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          supportEmail_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string support_email = 4;</code>
     *
     * <pre>
     * Email for user support
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSupportEmailBytes() {
      java.lang.Object ref = supportEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        supportEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string support_email = 4;</code>
     *
     * <pre>
     * Email for user support
     * </pre>
     */
    public Builder setSupportEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      supportEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string support_email = 4;</code>
     *
     * <pre>
     * Email for user support
     * </pre>
     */
    public Builder clearSupportEmail() {
      bitField0_ = (bitField0_ & ~0x00000008);
      supportEmail_ = getDefaultInstance().getSupportEmail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string support_email = 4;</code>
     *
     * <pre>
     * Email for user support
     * </pre>
     */
    public Builder setSupportEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      supportEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object blogUrl_ = "";
    /**
     * <code>optional string blog_url = 5;</code>
     *
     * <pre>
     * Blog URL
     * </pre>
     */
    public boolean hasBlogUrl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string blog_url = 5;</code>
     *
     * <pre>
     * Blog URL
     * </pre>
     */
    public java.lang.String getBlogUrl() {
      java.lang.Object ref = blogUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          blogUrl_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string blog_url = 5;</code>
     *
     * <pre>
     * Blog URL
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBlogUrlBytes() {
      java.lang.Object ref = blogUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blogUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string blog_url = 5;</code>
     *
     * <pre>
     * Blog URL
     * </pre>
     */
    public Builder setBlogUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      blogUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string blog_url = 5;</code>
     *
     * <pre>
     * Blog URL
     * </pre>
     */
    public Builder clearBlogUrl() {
      bitField0_ = (bitField0_ & ~0x00000010);
      blogUrl_ = getDefaultInstance().getBlogUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string blog_url = 5;</code>
     *
     * <pre>
     * Blog URL
     * </pre>
     */
    public Builder setBlogUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      blogUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object facebookUrl_ = "";
    /**
     * <code>optional string facebook_url = 6;</code>
     *
     * <pre>
     * Facebook page URL
     * </pre>
     */
    public boolean hasFacebookUrl() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string facebook_url = 6;</code>
     *
     * <pre>
     * Facebook page URL
     * </pre>
     */
    public java.lang.String getFacebookUrl() {
      java.lang.Object ref = facebookUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          facebookUrl_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string facebook_url = 6;</code>
     *
     * <pre>
     * Facebook page URL
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFacebookUrlBytes() {
      java.lang.Object ref = facebookUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        facebookUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string facebook_url = 6;</code>
     *
     * <pre>
     * Facebook page URL
     * </pre>
     */
    public Builder setFacebookUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      facebookUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string facebook_url = 6;</code>
     *
     * <pre>
     * Facebook page URL
     * </pre>
     */
    public Builder clearFacebookUrl() {
      bitField0_ = (bitField0_ & ~0x00000020);
      facebookUrl_ = getDefaultInstance().getFacebookUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string facebook_url = 6;</code>
     *
     * <pre>
     * Facebook page URL
     * </pre>
     */
    public Builder setFacebookUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      facebookUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object twitterHandle_ = "";
    /**
     * <code>optional string twitter_handle = 7;</code>
     *
     * <pre>
     * Twitter URL
     * </pre>
     */
    public boolean hasTwitterHandle() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string twitter_handle = 7;</code>
     *
     * <pre>
     * Twitter URL
     * </pre>
     */
    public java.lang.String getTwitterHandle() {
      java.lang.Object ref = twitterHandle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          twitterHandle_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string twitter_handle = 7;</code>
     *
     * <pre>
     * Twitter URL
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTwitterHandleBytes() {
      java.lang.Object ref = twitterHandle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        twitterHandle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string twitter_handle = 7;</code>
     *
     * <pre>
     * Twitter URL
     * </pre>
     */
    public Builder setTwitterHandle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      twitterHandle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string twitter_handle = 7;</code>
     *
     * <pre>
     * Twitter URL
     * </pre>
     */
    public Builder clearTwitterHandle() {
      bitField0_ = (bitField0_ & ~0x00000040);
      twitterHandle_ = getDefaultInstance().getTwitterHandle();
      onChanged();
      return this;
    }
    /**
     * <code>optional string twitter_handle = 7;</code>
     *
     * <pre>
     * Twitter URL
     * </pre>
     */
    public Builder setTwitterHandleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      twitterHandle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object feedUrl_ = "";
    /**
     * <code>optional string feed_url = 8;</code>
     *
     * <pre>
     * RSS Feed
     * </pre>
     */
    public boolean hasFeedUrl() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string feed_url = 8;</code>
     *
     * <pre>
     * RSS Feed
     * </pre>
     */
    public java.lang.String getFeedUrl() {
      java.lang.Object ref = feedUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          feedUrl_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string feed_url = 8;</code>
     *
     * <pre>
     * RSS Feed
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFeedUrlBytes() {
      java.lang.Object ref = feedUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        feedUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string feed_url = 8;</code>
     *
     * <pre>
     * RSS Feed
     * </pre>
     */
    public Builder setFeedUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      feedUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string feed_url = 8;</code>
     *
     * <pre>
     * RSS Feed
     * </pre>
     */
    public Builder clearFeedUrl() {
      bitField0_ = (bitField0_ & ~0x00000080);
      feedUrl_ = getDefaultInstance().getFeedUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string feed_url = 8;</code>
     *
     * <pre>
     * RSS Feed
     * </pre>
     */
    public Builder setFeedUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      feedUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mailResponderEmail_ = "";
    /**
     * <code>optional string mail_responder_email = 9;</code>
     *
     * <pre>
     * Email Address for tool delivery
     * </pre>
     */
    public boolean hasMailResponderEmail() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string mail_responder_email = 9;</code>
     *
     * <pre>
     * Email Address for tool delivery
     * </pre>
     */
    public java.lang.String getMailResponderEmail() {
      java.lang.Object ref = mailResponderEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mailResponderEmail_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string mail_responder_email = 9;</code>
     *
     * <pre>
     * Email Address for tool delivery
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMailResponderEmailBytes() {
      java.lang.Object ref = mailResponderEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mailResponderEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string mail_responder_email = 9;</code>
     *
     * <pre>
     * Email Address for tool delivery
     * </pre>
     */
    public Builder setMailResponderEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      mailResponderEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string mail_responder_email = 9;</code>
     *
     * <pre>
     * Email Address for tool delivery
     * </pre>
     */
    public Builder clearMailResponderEmail() {
      bitField0_ = (bitField0_ & ~0x00000100);
      mailResponderEmail_ = getDefaultInstance().getMailResponderEmail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string mail_responder_email = 9;</code>
     *
     * <pre>
     * Email Address for tool delivery
     * </pre>
     */
    public Builder setMailResponderEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      mailResponderEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceUrl_ = "";
    /**
     * <code>optional string source_url = 10;</code>
     *
     * <pre>
     * URL of the open source repo
     * </pre>
     */
    public boolean hasSourceUrl() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string source_url = 10;</code>
     *
     * <pre>
     * URL of the open source repo
     * </pre>
     */
    public java.lang.String getSourceUrl() {
      java.lang.Object ref = sourceUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceUrl_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string source_url = 10;</code>
     *
     * <pre>
     * URL of the open source repo
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSourceUrlBytes() {
      java.lang.Object ref = sourceUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string source_url = 10;</code>
     *
     * <pre>
     * URL of the open source repo
     * </pre>
     */
    public Builder setSourceUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      sourceUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string source_url = 10;</code>
     *
     * <pre>
     * URL of the open source repo
     * </pre>
     */
    public Builder clearSourceUrl() {
      bitField0_ = (bitField0_ & ~0x00000200);
      sourceUrl_ = getDefaultInstance().getSourceUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string source_url = 10;</code>
     *
     * <pre>
     * URL of the open source repo
     * </pre>
     */
    public Builder setSourceUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      sourceUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>optional string description = 11;</code>
     *
     * <pre>
     * Description text for the entity
     * </pre>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string description = 11;</code>
     *
     * <pre>
     * Description text for the entity
     * </pre>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string description = 11;</code>
     *
     * <pre>
     * Description text for the entity
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string description = 11;</code>
     *
     * <pre>
     * Description text for the entity
     * </pre>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 11;</code>
     *
     * <pre>
     * Description text for the entity
     * </pre>
     */
    public Builder clearDescription() {
      bitField0_ = (bitField0_ & ~0x00000400);
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 11;</code>
     *
     * <pre>
     * Description text for the entity
     * </pre>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      description_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.asl19.paskoocheh.Translation> translation_ =
      java.util.Collections.emptyList();
    private void ensureTranslationIsMutable() {
      if (!((bitField0_ & 0x00000800) == 0x00000800)) {
        translation_ = new java.util.ArrayList<org.asl19.paskoocheh.Translation>(translation_);
        bitField0_ |= 0x00000800;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.asl19.paskoocheh.Translation, org.asl19.paskoocheh.Translation.Builder, org.asl19.paskoocheh.TranslationOrBuilder> translationBuilder_;

    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public java.util.List<org.asl19.paskoocheh.Translation> getTranslationList() {
      if (translationBuilder_ == null) {
        return java.util.Collections.unmodifiableList(translation_);
      } else {
        return translationBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public int getTranslationCount() {
      if (translationBuilder_ == null) {
        return translation_.size();
      } else {
        return translationBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public org.asl19.paskoocheh.Translation getTranslation(int index) {
      if (translationBuilder_ == null) {
        return translation_.get(index);
      } else {
        return translationBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public Builder setTranslation(
        int index, org.asl19.paskoocheh.Translation value) {
      if (translationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTranslationIsMutable();
        translation_.set(index, value);
        onChanged();
      } else {
        translationBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public Builder setTranslation(
        int index, org.asl19.paskoocheh.Translation.Builder builderForValue) {
      if (translationBuilder_ == null) {
        ensureTranslationIsMutable();
        translation_.set(index, builderForValue.build());
        onChanged();
      } else {
        translationBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public Builder addTranslation(org.asl19.paskoocheh.Translation value) {
      if (translationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTranslationIsMutable();
        translation_.add(value);
        onChanged();
      } else {
        translationBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public Builder addTranslation(
        int index, org.asl19.paskoocheh.Translation value) {
      if (translationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTranslationIsMutable();
        translation_.add(index, value);
        onChanged();
      } else {
        translationBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public Builder addTranslation(
        org.asl19.paskoocheh.Translation.Builder builderForValue) {
      if (translationBuilder_ == null) {
        ensureTranslationIsMutable();
        translation_.add(builderForValue.build());
        onChanged();
      } else {
        translationBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public Builder addTranslation(
        int index, org.asl19.paskoocheh.Translation.Builder builderForValue) {
      if (translationBuilder_ == null) {
        ensureTranslationIsMutable();
        translation_.add(index, builderForValue.build());
        onChanged();
      } else {
        translationBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public Builder addAllTranslation(
        java.lang.Iterable<? extends org.asl19.paskoocheh.Translation> values) {
      if (translationBuilder_ == null) {
        ensureTranslationIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, translation_);
        onChanged();
      } else {
        translationBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public Builder clearTranslation() {
      if (translationBuilder_ == null) {
        translation_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
      } else {
        translationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public Builder removeTranslation(int index) {
      if (translationBuilder_ == null) {
        ensureTranslationIsMutable();
        translation_.remove(index);
        onChanged();
      } else {
        translationBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public org.asl19.paskoocheh.Translation.Builder getTranslationBuilder(
        int index) {
      return getTranslationFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public org.asl19.paskoocheh.TranslationOrBuilder getTranslationOrBuilder(
        int index) {
      if (translationBuilder_ == null) {
        return translation_.get(index);  } else {
        return translationBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public java.util.List<? extends org.asl19.paskoocheh.TranslationOrBuilder> 
         getTranslationOrBuilderList() {
      if (translationBuilder_ != null) {
        return translationBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(translation_);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public org.asl19.paskoocheh.Translation.Builder addTranslationBuilder() {
      return getTranslationFieldBuilder().addBuilder(
          org.asl19.paskoocheh.Translation.getDefaultInstance());
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public org.asl19.paskoocheh.Translation.Builder addTranslationBuilder(
        int index) {
      return getTranslationFieldBuilder().addBuilder(
          index, org.asl19.paskoocheh.Translation.getDefaultInstance());
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
     *
     * <pre>
     * Language specific information
     * </pre>
     */
    public java.util.List<org.asl19.paskoocheh.Translation.Builder> 
         getTranslationBuilderList() {
      return getTranslationFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.asl19.paskoocheh.Translation, org.asl19.paskoocheh.Translation.Builder, org.asl19.paskoocheh.TranslationOrBuilder> 
        getTranslationFieldBuilder() {
      if (translationBuilder_ == null) {
        translationBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.asl19.paskoocheh.Translation, org.asl19.paskoocheh.Translation.Builder, org.asl19.paskoocheh.TranslationOrBuilder>(
                translation_,
                ((bitField0_ & 0x00000800) == 0x00000800),
                getParentForChildren(),
                isClean());
        translation_ = null;
      }
      return translationBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.asl19.paskoocheh.Contact)
  }

  static {
    defaultInstance = new Contact(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.asl19.paskoocheh.Contact)
}

