// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paskoocheh.proto

package org.asl19.paskoocheh;

public interface ContactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.asl19.paskoocheh.Contact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   *
   * <pre>
   * Name of the entity
   * </pre>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   *
   * <pre>
   * Name of the entity
   * </pre>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   *
   * <pre>
   * Name of the entity
   * </pre>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string website_url = 2;</code>
   *
   * <pre>
   * Website URL
   * </pre>
   */
  boolean hasWebsiteUrl();
  /**
   * <code>optional string website_url = 2;</code>
   *
   * <pre>
   * Website URL
   * </pre>
   */
  java.lang.String getWebsiteUrl();
  /**
   * <code>optional string website_url = 2;</code>
   *
   * <pre>
   * Website URL
   * </pre>
   */
  com.google.protobuf.ByteString
      getWebsiteUrlBytes();

  /**
   * <code>optional string user_support_url = 3;</code>
   *
   * <pre>
   * URL for user support
   * </pre>
   */
  boolean hasUserSupportUrl();
  /**
   * <code>optional string user_support_url = 3;</code>
   *
   * <pre>
   * URL for user support
   * </pre>
   */
  java.lang.String getUserSupportUrl();
  /**
   * <code>optional string user_support_url = 3;</code>
   *
   * <pre>
   * URL for user support
   * </pre>
   */
  com.google.protobuf.ByteString
      getUserSupportUrlBytes();

  /**
   * <code>optional string support_email = 4;</code>
   *
   * <pre>
   * Email for user support
   * </pre>
   */
  boolean hasSupportEmail();
  /**
   * <code>optional string support_email = 4;</code>
   *
   * <pre>
   * Email for user support
   * </pre>
   */
  java.lang.String getSupportEmail();
  /**
   * <code>optional string support_email = 4;</code>
   *
   * <pre>
   * Email for user support
   * </pre>
   */
  com.google.protobuf.ByteString
      getSupportEmailBytes();

  /**
   * <code>optional string blog_url = 5;</code>
   *
   * <pre>
   * Blog URL
   * </pre>
   */
  boolean hasBlogUrl();
  /**
   * <code>optional string blog_url = 5;</code>
   *
   * <pre>
   * Blog URL
   * </pre>
   */
  java.lang.String getBlogUrl();
  /**
   * <code>optional string blog_url = 5;</code>
   *
   * <pre>
   * Blog URL
   * </pre>
   */
  com.google.protobuf.ByteString
      getBlogUrlBytes();

  /**
   * <code>optional string facebook_url = 6;</code>
   *
   * <pre>
   * Facebook page URL
   * </pre>
   */
  boolean hasFacebookUrl();
  /**
   * <code>optional string facebook_url = 6;</code>
   *
   * <pre>
   * Facebook page URL
   * </pre>
   */
  java.lang.String getFacebookUrl();
  /**
   * <code>optional string facebook_url = 6;</code>
   *
   * <pre>
   * Facebook page URL
   * </pre>
   */
  com.google.protobuf.ByteString
      getFacebookUrlBytes();

  /**
   * <code>optional string twitter_handle = 7;</code>
   *
   * <pre>
   * Twitter URL
   * </pre>
   */
  boolean hasTwitterHandle();
  /**
   * <code>optional string twitter_handle = 7;</code>
   *
   * <pre>
   * Twitter URL
   * </pre>
   */
  java.lang.String getTwitterHandle();
  /**
   * <code>optional string twitter_handle = 7;</code>
   *
   * <pre>
   * Twitter URL
   * </pre>
   */
  com.google.protobuf.ByteString
      getTwitterHandleBytes();

  /**
   * <code>optional string feed_url = 8;</code>
   *
   * <pre>
   * RSS Feed
   * </pre>
   */
  boolean hasFeedUrl();
  /**
   * <code>optional string feed_url = 8;</code>
   *
   * <pre>
   * RSS Feed
   * </pre>
   */
  java.lang.String getFeedUrl();
  /**
   * <code>optional string feed_url = 8;</code>
   *
   * <pre>
   * RSS Feed
   * </pre>
   */
  com.google.protobuf.ByteString
      getFeedUrlBytes();

  /**
   * <code>optional string mail_responder_email = 9;</code>
   *
   * <pre>
   * Email Address for tool delivery
   * </pre>
   */
  boolean hasMailResponderEmail();
  /**
   * <code>optional string mail_responder_email = 9;</code>
   *
   * <pre>
   * Email Address for tool delivery
   * </pre>
   */
  java.lang.String getMailResponderEmail();
  /**
   * <code>optional string mail_responder_email = 9;</code>
   *
   * <pre>
   * Email Address for tool delivery
   * </pre>
   */
  com.google.protobuf.ByteString
      getMailResponderEmailBytes();

  /**
   * <code>optional string source_url = 10;</code>
   *
   * <pre>
   * URL of the open source repo
   * </pre>
   */
  boolean hasSourceUrl();
  /**
   * <code>optional string source_url = 10;</code>
   *
   * <pre>
   * URL of the open source repo
   * </pre>
   */
  java.lang.String getSourceUrl();
  /**
   * <code>optional string source_url = 10;</code>
   *
   * <pre>
   * URL of the open source repo
   * </pre>
   */
  com.google.protobuf.ByteString
      getSourceUrlBytes();

  /**
   * <code>optional string description = 11;</code>
   *
   * <pre>
   * Description text for the entity
   * </pre>
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 11;</code>
   *
   * <pre>
   * Description text for the entity
   * </pre>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 11;</code>
   *
   * <pre>
   * Description text for the entity
   * </pre>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
   *
   * <pre>
   * Language specific information
   * </pre>
   */
  java.util.List<org.asl19.paskoocheh.Translation> 
      getTranslationList();
  /**
   * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
   *
   * <pre>
   * Language specific information
   * </pre>
   */
  org.asl19.paskoocheh.Translation getTranslation(int index);
  /**
   * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
   *
   * <pre>
   * Language specific information
   * </pre>
   */
  int getTranslationCount();
  /**
   * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
   *
   * <pre>
   * Language specific information
   * </pre>
   */
  java.util.List<? extends org.asl19.paskoocheh.TranslationOrBuilder> 
      getTranslationOrBuilderList();
  /**
   * <code>repeated .org.asl19.paskoocheh.Translation translation = 12;</code>
   *
   * <pre>
   * Language specific information
   * </pre>
   */
  org.asl19.paskoocheh.TranslationOrBuilder getTranslationOrBuilder(
      int index);
}
