// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paskoocheh.proto

package org.asl19.paskoocheh;

/**
 * Protobuf type {@code org.asl19.paskoocheh.Faq}
 *
 * <pre>
 * FAQ for tools
 * </pre>
 */
public final class Faq extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.asl19.paskoocheh.Faq)
    FaqOrBuilder {
  // Use Faq.newBuilder() to construct.
  private Faq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Faq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Faq defaultInstance;
  public static Faq getDefaultInstance() {
    return defaultInstance;
  }

  public Faq getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Faq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            lang_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            question_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            answer_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Faq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Faq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.asl19.paskoocheh.Faq.class, org.asl19.paskoocheh.Faq.Builder.class);
  }

  public static com.google.protobuf.Parser<Faq> PARSER =
      new com.google.protobuf.AbstractParser<Faq>() {
    public Faq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Faq(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Faq> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int LANG_FIELD_NUMBER = 1;
  private java.lang.Object lang_;
  /**
   * <code>required string lang = 1;</code>
   *
   * <pre>
   * Language of the Q and A
   * </pre>
   */
  public boolean hasLang() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string lang = 1;</code>
   *
   * <pre>
   * Language of the Q and A
   * </pre>
   */
  public java.lang.String getLang() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        lang_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string lang = 1;</code>
   *
   * <pre>
   * Language of the Q and A
   * </pre>
   */
  public com.google.protobuf.ByteString
      getLangBytes() {
    java.lang.Object ref = lang_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lang_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUESTION_FIELD_NUMBER = 2;
  private java.lang.Object question_;
  /**
   * <code>required string question = 2;</code>
   *
   * <pre>
   * Question!
   * </pre>
   */
  public boolean hasQuestion() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string question = 2;</code>
   *
   * <pre>
   * Question!
   * </pre>
   */
  public java.lang.String getQuestion() {
    java.lang.Object ref = question_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        question_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string question = 2;</code>
   *
   * <pre>
   * Question!
   * </pre>
   */
  public com.google.protobuf.ByteString
      getQuestionBytes() {
    java.lang.Object ref = question_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      question_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANSWER_FIELD_NUMBER = 3;
  private java.lang.Object answer_;
  /**
   * <code>required string answer = 3;</code>
   *
   * <pre>
   * Answer!
   * </pre>
   */
  public boolean hasAnswer() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required string answer = 3;</code>
   *
   * <pre>
   * Answer!
   * </pre>
   */
  public java.lang.String getAnswer() {
    java.lang.Object ref = answer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        answer_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string answer = 3;</code>
   *
   * <pre>
   * Answer!
   * </pre>
   */
  public com.google.protobuf.ByteString
      getAnswerBytes() {
    java.lang.Object ref = answer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      answer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    lang_ = "";
    question_ = "";
    answer_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasLang()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasQuestion()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAnswer()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getLangBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getQuestionBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getAnswerBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getLangBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getQuestionBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getAnswerBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.asl19.paskoocheh.Faq)) {
      return super.equals(obj);
    }
    org.asl19.paskoocheh.Faq other = (org.asl19.paskoocheh.Faq) obj;

    boolean result = true;
    result = result && (hasLang() == other.hasLang());
    if (hasLang()) {
      result = result && getLang()
          .equals(other.getLang());
    }
    result = result && (hasQuestion() == other.hasQuestion());
    if (hasQuestion()) {
      result = result && getQuestion()
          .equals(other.getQuestion());
    }
    result = result && (hasAnswer() == other.hasAnswer());
    if (hasAnswer()) {
      result = result && getAnswer()
          .equals(other.getAnswer());
    }
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasLang()) {
      hash = (37 * hash) + LANG_FIELD_NUMBER;
      hash = (53 * hash) + getLang().hashCode();
    }
    if (hasQuestion()) {
      hash = (37 * hash) + QUESTION_FIELD_NUMBER;
      hash = (53 * hash) + getQuestion().hashCode();
    }
    if (hasAnswer()) {
      hash = (37 * hash) + ANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getAnswer().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.asl19.paskoocheh.Faq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.asl19.paskoocheh.Faq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Faq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.asl19.paskoocheh.Faq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Faq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.asl19.paskoocheh.Faq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Faq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.asl19.paskoocheh.Faq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Faq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.asl19.paskoocheh.Faq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.asl19.paskoocheh.Faq prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.asl19.paskoocheh.Faq}
   *
   * <pre>
   * FAQ for tools
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.asl19.paskoocheh.Faq)
      org.asl19.paskoocheh.FaqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Faq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Faq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.asl19.paskoocheh.Faq.class, org.asl19.paskoocheh.Faq.Builder.class);
    }

    // Construct using org.asl19.paskoocheh.Faq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      lang_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      question_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      answer_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Faq_descriptor;
    }

    public org.asl19.paskoocheh.Faq getDefaultInstanceForType() {
      return org.asl19.paskoocheh.Faq.getDefaultInstance();
    }

    public org.asl19.paskoocheh.Faq build() {
      org.asl19.paskoocheh.Faq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.asl19.paskoocheh.Faq buildPartial() {
      org.asl19.paskoocheh.Faq result = new org.asl19.paskoocheh.Faq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.lang_ = lang_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.question_ = question_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.answer_ = answer_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.asl19.paskoocheh.Faq) {
        return mergeFrom((org.asl19.paskoocheh.Faq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.asl19.paskoocheh.Faq other) {
      if (other == org.asl19.paskoocheh.Faq.getDefaultInstance()) return this;
      if (other.hasLang()) {
        bitField0_ |= 0x00000001;
        lang_ = other.lang_;
        onChanged();
      }
      if (other.hasQuestion()) {
        bitField0_ |= 0x00000002;
        question_ = other.question_;
        onChanged();
      }
      if (other.hasAnswer()) {
        bitField0_ |= 0x00000004;
        answer_ = other.answer_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasLang()) {
        
        return false;
      }
      if (!hasQuestion()) {
        
        return false;
      }
      if (!hasAnswer()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.asl19.paskoocheh.Faq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.asl19.paskoocheh.Faq) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object lang_ = "";
    /**
     * <code>required string lang = 1;</code>
     *
     * <pre>
     * Language of the Q and A
     * </pre>
     */
    public boolean hasLang() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string lang = 1;</code>
     *
     * <pre>
     * Language of the Q and A
     * </pre>
     */
    public java.lang.String getLang() {
      java.lang.Object ref = lang_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lang_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string lang = 1;</code>
     *
     * <pre>
     * Language of the Q and A
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string lang = 1;</code>
     *
     * <pre>
     * Language of the Q and A
     * </pre>
     */
    public Builder setLang(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      lang_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string lang = 1;</code>
     *
     * <pre>
     * Language of the Q and A
     * </pre>
     */
    public Builder clearLang() {
      bitField0_ = (bitField0_ & ~0x00000001);
      lang_ = getDefaultInstance().getLang();
      onChanged();
      return this;
    }
    /**
     * <code>required string lang = 1;</code>
     *
     * <pre>
     * Language of the Q and A
     * </pre>
     */
    public Builder setLangBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      lang_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object question_ = "";
    /**
     * <code>required string question = 2;</code>
     *
     * <pre>
     * Question!
     * </pre>
     */
    public boolean hasQuestion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string question = 2;</code>
     *
     * <pre>
     * Question!
     * </pre>
     */
    public java.lang.String getQuestion() {
      java.lang.Object ref = question_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          question_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string question = 2;</code>
     *
     * <pre>
     * Question!
     * </pre>
     */
    public com.google.protobuf.ByteString
        getQuestionBytes() {
      java.lang.Object ref = question_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        question_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string question = 2;</code>
     *
     * <pre>
     * Question!
     * </pre>
     */
    public Builder setQuestion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      question_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string question = 2;</code>
     *
     * <pre>
     * Question!
     * </pre>
     */
    public Builder clearQuestion() {
      bitField0_ = (bitField0_ & ~0x00000002);
      question_ = getDefaultInstance().getQuestion();
      onChanged();
      return this;
    }
    /**
     * <code>required string question = 2;</code>
     *
     * <pre>
     * Question!
     * </pre>
     */
    public Builder setQuestionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      question_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object answer_ = "";
    /**
     * <code>required string answer = 3;</code>
     *
     * <pre>
     * Answer!
     * </pre>
     */
    public boolean hasAnswer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string answer = 3;</code>
     *
     * <pre>
     * Answer!
     * </pre>
     */
    public java.lang.String getAnswer() {
      java.lang.Object ref = answer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          answer_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string answer = 3;</code>
     *
     * <pre>
     * Answer!
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAnswerBytes() {
      java.lang.Object ref = answer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string answer = 3;</code>
     *
     * <pre>
     * Answer!
     * </pre>
     */
    public Builder setAnswer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      answer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string answer = 3;</code>
     *
     * <pre>
     * Answer!
     * </pre>
     */
    public Builder clearAnswer() {
      bitField0_ = (bitField0_ & ~0x00000004);
      answer_ = getDefaultInstance().getAnswer();
      onChanged();
      return this;
    }
    /**
     * <code>required string answer = 3;</code>
     *
     * <pre>
     * Answer!
     * </pre>
     */
    public Builder setAnswerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      answer_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.asl19.paskoocheh.Faq)
  }

  static {
    defaultInstance = new Faq(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.asl19.paskoocheh.Faq)
}

