// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paskoocheh.proto

package org.asl19.paskoocheh;

public interface FaqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.asl19.paskoocheh.Faq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string lang = 1;</code>
   *
   * <pre>
   * Language of the Q and A
   * </pre>
   */
  boolean hasLang();
  /**
   * <code>required string lang = 1;</code>
   *
   * <pre>
   * Language of the Q and A
   * </pre>
   */
  java.lang.String getLang();
  /**
   * <code>required string lang = 1;</code>
   *
   * <pre>
   * Language of the Q and A
   * </pre>
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <code>required string question = 2;</code>
   *
   * <pre>
   * Question!
   * </pre>
   */
  boolean hasQuestion();
  /**
   * <code>required string question = 2;</code>
   *
   * <pre>
   * Question!
   * </pre>
   */
  java.lang.String getQuestion();
  /**
   * <code>required string question = 2;</code>
   *
   * <pre>
   * Question!
   * </pre>
   */
  com.google.protobuf.ByteString
      getQuestionBytes();

  /**
   * <code>required string answer = 3;</code>
   *
   * <pre>
   * Answer!
   * </pre>
   */
  boolean hasAnswer();
  /**
   * <code>required string answer = 3;</code>
   *
   * <pre>
   * Answer!
   * </pre>
   */
  java.lang.String getAnswer();
  /**
   * <code>required string answer = 3;</code>
   *
   * <pre>
   * Answer!
   * </pre>
   */
  com.google.protobuf.ByteString
      getAnswerBytes();
}
