// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paskoocheh.proto

package org.asl19.paskoocheh;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.asl19.paskoocheh.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string text = 1;</code>
   *
   * <pre>
   * Text of the message
   * </pre>
   */
  boolean hasText();
  /**
   * <code>required string text = 1;</code>
   *
   * <pre>
   * Text of the message
   * </pre>
   */
  java.lang.String getText();
  /**
   * <code>required string text = 1;</code>
   *
   * <pre>
   * Text of the message
   * </pre>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>required int64 date_published = 2;</code>
   *
   * <pre>
   * Date the message published
   * </pre>
   */
  boolean hasDatePublished();
  /**
   * <code>required int64 date_published = 2;</code>
   *
   * <pre>
   * Date the message published
   * </pre>
   */
  long getDatePublished();

  /**
   * <code>required .org.asl19.paskoocheh.PriorityLevel priority = 3;</code>
   *
   * <pre>
   * Priority of the message
   * </pre>
   */
  boolean hasPriority();
  /**
   * <code>required .org.asl19.paskoocheh.PriorityLevel priority = 3;</code>
   *
   * <pre>
   * Priority of the message
   * </pre>
   */
  org.asl19.paskoocheh.PriorityLevel getPriority();
}
