// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paskoocheh.proto

package org.asl19.paskoocheh;

public final class Paskoocheh {
  private Paskoocheh() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_asl19_paskoocheh_Message_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_asl19_paskoocheh_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_asl19_paskoocheh_BinaryFile_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_asl19_paskoocheh_BinaryFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_asl19_paskoocheh_Faq_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_asl19_paskoocheh_Faq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_asl19_paskoocheh_Translation_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_asl19_paskoocheh_Translation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_asl19_paskoocheh_Contact_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_asl19_paskoocheh_Contact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_asl19_paskoocheh_Config_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_asl19_paskoocheh_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_asl19_paskoocheh_Platform_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_asl19_paskoocheh_Platform_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_asl19_paskoocheh_Tool_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_asl19_paskoocheh_Tool_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_asl19_paskoocheh_Release_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_asl19_paskoocheh_Release_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020paskoocheh.proto\022\024org.asl19.paskoocheh" +
      "\"f\n\007Message\022\014\n\004text\030\001 \002(\t\022\026\n\016date_publis" +
      "hed\030\002 \002(\003\0225\n\010priority\030\003 \002(\0162#.org.asl19." +
      "paskoocheh.PriorityLevel\":\n\nBinaryFile\022\020" +
      "\n\010checksum\030\001 \002(\t\022\014\n\004size\030\002 \002(\003\022\014\n\004path\030\003" +
      " \002(\t\"5\n\003Faq\022\014\n\004lang\030\001 \002(\t\022\020\n\010question\030\002 " +
      "\002(\t\022\016\n\006answer\030\003 \002(\t\">\n\013Translation\022\014\n\004la" +
      "ng\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\023\n\013description\030\003 " +
      "\001(\t\"\256\002\n\007Contact\022\014\n\004name\030\001 \002(\t\022\023\n\013website" +
      "_url\030\002 \001(\t\022\030\n\020user_support_url\030\003 \001(\t\022\025\n\r",
      "support_email\030\004 \001(\t\022\020\n\010blog_url\030\005 \001(\t\022\024\n" +
      "\014facebook_url\030\006 \001(\t\022\026\n\016twitter_handle\030\007 " +
      "\001(\t\022\020\n\010feed_url\030\010 \001(\t\022\034\n\024mail_responder_" +
      "email\030\t \001(\t\022\022\n\nsource_url\030\n \001(\t\022\023\n\013descr" +
      "iption\030\013 \001(\t\0226\n\013translation\030\014 \003(\0132!.org." +
      "asl19.paskoocheh.Translation\"\233\001\n\006Config\022" +
      "\016\n\006bucket\030\001 \002(\t\022\017\n\007version\030\002 \002(\t\022\016\n\006imag" +
      "es\030\003 \003(\t\0221\n\tplatforms\030\004 \003(\0132\036.org.asl19." +
      "paskoocheh.Platform\022-\n\006update\030\024 \003(\0132\035.or" +
      "g.asl19.paskoocheh.Message\"\310\001\n\010Platform\022",
      "0\n\004name\030\001 \002(\0162\".org.asl19.paskoocheh.Pla" +
      "tformName\0220\n\004type\030\002 \002(\0162\".org.asl19.pask" +
      "oocheh.PlatformType\022)\n\005tools\030\003 \003(\0132\032.org" +
      ".asl19.paskoocheh.Tool\022-\n\006update\030\024 \003(\0132\035" +
      ".org.asl19.paskoocheh.Message\"\357\002\n\004Tool\022." +
      "\n\007contact\030\001 \002(\0132\035.org.asl19.paskoocheh.C" +
      "ontact\022-\n\005types\030\002 \003(\0162\036.org.asl19.paskoo" +
      "cheh.ToolType\022\014\n\004tags\030\003 \003(\t\022\025\n\ris_openso" +
      "urce\030\004 \002(\010\022\026\n\016is_recommended\030\005 \002(\010\022\023\n\013is" +
      "_featured\030\006 \002(\010\022\'\n\004faqs\030\010 \003(\0132\031.org.asl1",
      "9.paskoocheh.Faq\022-\n\006vendor\030\t \002(\0132\035.org.a" +
      "sl19.paskoocheh.Contact\022/\n\010releases\030\n \003(" +
      "\0132\035.org.asl19.paskoocheh.Release\022-\n\006upda" +
      "te\030\024 \003(\0132\035.org.asl19.paskoocheh.Message\"" +
      "\337\002\n\007Release\022\017\n\007version\030\001 \002(\t\022\024\n\014date_cre" +
      "ated\030\002 \002(\003\0220\n\006binary\030\003 \002(\0132 .org.asl19.p" +
      "askoocheh.BinaryFile\022\016\n\006rating\030\004 \001(\002\022\026\n\016" +
      "download_count\030\005 \001(\003\022\014\n\004icon\030\006 \001(\t\022\025\n\rda" +
      "te_modified\030\007 \001(\003\022\025\n\rdate_released\030\010 \002(\003" +
      "\022\023\n\013release_url\030\t \002(\t\022\023\n\013screenshots\030\n \003",
      "(\t\022\021\n\ttutorials\030\013 \003(\t\022\024\n\014package_name\030\014 " +
      "\001(\t\022\025\n\rbuild_version\030\r \001(\005\022-\n\006update\030\024 \003" +
      "(\0132\035.org.asl19.paskoocheh.Message*<\n\010Too" +
      "lType\022\007\n\003VPN\020\000\022\t\n\005PROXY\020\001\022\r\n\tMESSENGER\020\002" +
      "\022\r\n\tANONIMITY\020\003*4\n\014PlatformType\022\013\n\007DESKT" +
      "OP\020\000\022\n\n\006MOBILE\020\001\022\013\n\007BROWSER\020\002*\230\001\n\014Platfo" +
      "rmName\022\013\n\007WINDOWS\020\000\022\t\n\005MACOS\020\001\022\014\n\010LINUX_" +
      "64\020\002\022\014\n\010LINUX_32\020\003\022\013\n\007ANDROID\020\005\022\007\n\003IOS\020\006" +
      "\022\022\n\016WINDOWS_MOBILE\020\007\022\n\n\006CHROME\020\n\022\013\n\007FIRE" +
      "FOX\020\013\022\006\n\002IE\020\014\022\t\n\005OPERA\020\r*.\n\rPriorityLeve",
      "l\022\010\n\004HIGH\020\000\022\n\n\006MEDIUM\020\001\022\007\n\003LOW\020\002B\005P\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_asl19_paskoocheh_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_asl19_paskoocheh_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_asl19_paskoocheh_Message_descriptor,
        new java.lang.String[] { "Text", "DatePublished", "Priority", });
    internal_static_org_asl19_paskoocheh_BinaryFile_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_asl19_paskoocheh_BinaryFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_asl19_paskoocheh_BinaryFile_descriptor,
        new java.lang.String[] { "Checksum", "Size", "Path", });
    internal_static_org_asl19_paskoocheh_Faq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_asl19_paskoocheh_Faq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_asl19_paskoocheh_Faq_descriptor,
        new java.lang.String[] { "Lang", "Question", "Answer", });
    internal_static_org_asl19_paskoocheh_Translation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_asl19_paskoocheh_Translation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_asl19_paskoocheh_Translation_descriptor,
        new java.lang.String[] { "Lang", "Name", "Description", });
    internal_static_org_asl19_paskoocheh_Contact_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_asl19_paskoocheh_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_asl19_paskoocheh_Contact_descriptor,
        new java.lang.String[] { "Name", "WebsiteUrl", "UserSupportUrl", "SupportEmail", "BlogUrl", "FacebookUrl", "TwitterHandle", "FeedUrl", "MailResponderEmail", "SourceUrl", "Description", "Translation", });
    internal_static_org_asl19_paskoocheh_Config_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_asl19_paskoocheh_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_asl19_paskoocheh_Config_descriptor,
        new java.lang.String[] { "Bucket", "Version", "Images", "Platforms", "Update", });
    internal_static_org_asl19_paskoocheh_Platform_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_asl19_paskoocheh_Platform_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_asl19_paskoocheh_Platform_descriptor,
        new java.lang.String[] { "Name", "Type", "Tools", "Update", });
    internal_static_org_asl19_paskoocheh_Tool_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_asl19_paskoocheh_Tool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_asl19_paskoocheh_Tool_descriptor,
        new java.lang.String[] { "Contact", "Types", "Tags", "IsOpensource", "IsRecommended", "IsFeatured", "Faqs", "Vendor", "Releases", "Update", });
    internal_static_org_asl19_paskoocheh_Release_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_org_asl19_paskoocheh_Release_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_asl19_paskoocheh_Release_descriptor,
        new java.lang.String[] { "Version", "DateCreated", "Binary", "Rating", "DownloadCount", "Icon", "DateModified", "DateReleased", "ReleaseUrl", "Screenshots", "Tutorials", "PackageName", "BuildVersion", "Update", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
