// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paskoocheh.proto

package org.asl19.paskoocheh;

/**
 * Protobuf enum {@code org.asl19.paskoocheh.PlatformName}
 *
 * <pre>
 * Various platforms for each platform type
 * </pre>
 */
public enum PlatformName
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>WINDOWS = 0;</code>
   *
   * <pre>
   * OS
   * </pre>
   */
  WINDOWS(0, 0),
  /**
   * <code>MACOS = 1;</code>
   */
  MACOS(1, 1),
  /**
   * <code>LINUX_64 = 2;</code>
   */
  LINUX_64(2, 2),
  /**
   * <code>LINUX_32 = 3;</code>
   */
  LINUX_32(3, 3),
  /**
   * <code>ANDROID = 5;</code>
   *
   * <pre>
   * Platform
   * </pre>
   */
  ANDROID(4, 5),
  /**
   * <code>IOS = 6;</code>
   */
  IOS(5, 6),
  /**
   * <code>WINDOWS_MOBILE = 7;</code>
   */
  WINDOWS_MOBILE(6, 7),
  /**
   * <code>CHROME = 10;</code>
   *
   * <pre>
   * Browser
   * </pre>
   */
  CHROME(7, 10),
  /**
   * <code>FIREFOX = 11;</code>
   */
  FIREFOX(8, 11),
  /**
   * <code>IE = 12;</code>
   */
  IE(9, 12),
  /**
   * <code>OPERA = 13;</code>
   */
  OPERA(10, 13),
  ;

  /**
   * <code>WINDOWS = 0;</code>
   *
   * <pre>
   * OS
   * </pre>
   */
  public static final int WINDOWS_VALUE = 0;
  /**
   * <code>MACOS = 1;</code>
   */
  public static final int MACOS_VALUE = 1;
  /**
   * <code>LINUX_64 = 2;</code>
   */
  public static final int LINUX_64_VALUE = 2;
  /**
   * <code>LINUX_32 = 3;</code>
   */
  public static final int LINUX_32_VALUE = 3;
  /**
   * <code>ANDROID = 5;</code>
   *
   * <pre>
   * Platform
   * </pre>
   */
  public static final int ANDROID_VALUE = 5;
  /**
   * <code>IOS = 6;</code>
   */
  public static final int IOS_VALUE = 6;
  /**
   * <code>WINDOWS_MOBILE = 7;</code>
   */
  public static final int WINDOWS_MOBILE_VALUE = 7;
  /**
   * <code>CHROME = 10;</code>
   *
   * <pre>
   * Browser
   * </pre>
   */
  public static final int CHROME_VALUE = 10;
  /**
   * <code>FIREFOX = 11;</code>
   */
  public static final int FIREFOX_VALUE = 11;
  /**
   * <code>IE = 12;</code>
   */
  public static final int IE_VALUE = 12;
  /**
   * <code>OPERA = 13;</code>
   */
  public static final int OPERA_VALUE = 13;


  public final int getNumber() { return value; }

  public static PlatformName valueOf(int value) {
    switch (value) {
      case 0: return WINDOWS;
      case 1: return MACOS;
      case 2: return LINUX_64;
      case 3: return LINUX_32;
      case 5: return ANDROID;
      case 6: return IOS;
      case 7: return WINDOWS_MOBILE;
      case 10: return CHROME;
      case 11: return FIREFOX;
      case 12: return IE;
      case 13: return OPERA;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PlatformName>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<PlatformName>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PlatformName>() {
          public PlatformName findValueByNumber(int number) {
            return PlatformName.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.asl19.paskoocheh.Paskoocheh.getDescriptor()
        .getEnumTypes().get(2);
  }

  private static final PlatformName[] VALUES = values();

  public static PlatformName valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private PlatformName(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.asl19.paskoocheh.PlatformName)
}

