// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paskoocheh.proto

package org.asl19.paskoocheh;

/**
 * Protobuf type {@code org.asl19.paskoocheh.Release}
 */
public final class Release extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.asl19.paskoocheh.Release)
    ReleaseOrBuilder {
  // Use Release.newBuilder() to construct.
  private Release(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Release(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Release defaultInstance;
  public static Release getDefaultInstance() {
    return defaultInstance;
  }

  public Release getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Release(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            version_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            dateCreated_ = input.readInt64();
            break;
          }
          case 26: {
            org.asl19.paskoocheh.BinaryFile.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = binary_.toBuilder();
            }
            binary_ = input.readMessage(org.asl19.paskoocheh.BinaryFile.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(binary_);
              binary_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 37: {
            bitField0_ |= 0x00000008;
            rating_ = input.readFloat();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            downloadCount_ = input.readInt64();
            break;
          }
          case 50: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000020;
            icon_ = bs;
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            dateModified_ = input.readInt64();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            dateReleased_ = input.readInt64();
            break;
          }
          case 74: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000100;
            releaseUrl_ = bs;
            break;
          }
          case 82: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              screenshots_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000200;
            }
            screenshots_.add(bs);
            break;
          }
          case 90: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
              tutorials_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000400;
            }
            tutorials_.add(bs);
            break;
          }
          case 98: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000200;
            packageName_ = bs;
            break;
          }
          case 104: {
            bitField0_ |= 0x00000400;
            buildVersion_ = input.readInt32();
            break;
          }
          case 162: {
            if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
              update_ = new java.util.ArrayList<org.asl19.paskoocheh.Message>();
              mutable_bitField0_ |= 0x00002000;
            }
            update_.add(input.readMessage(org.asl19.paskoocheh.Message.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
        screenshots_ = screenshots_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
        tutorials_ = tutorials_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
        update_ = java.util.Collections.unmodifiableList(update_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Release_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Release_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.asl19.paskoocheh.Release.class, org.asl19.paskoocheh.Release.Builder.class);
  }

  public static com.google.protobuf.Parser<Release> PARSER =
      new com.google.protobuf.AbstractParser<Release>() {
    public Release parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Release(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Release> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private java.lang.Object version_;
  /**
   * <code>required string version = 1;</code>
   *
   * <pre>
   * Version of the release
   * </pre>
   */
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string version = 1;</code>
   *
   * <pre>
   * Version of the release
   * </pre>
   */
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        version_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string version = 1;</code>
   *
   * <pre>
   * Version of the release
   * </pre>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_CREATED_FIELD_NUMBER = 2;
  private long dateCreated_;
  /**
   * <code>required int64 date_created = 2;</code>
   *
   * <pre>
   * Date the file uploaded in unix time
   * </pre>
   */
  public boolean hasDateCreated() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int64 date_created = 2;</code>
   *
   * <pre>
   * Date the file uploaded in unix time
   * </pre>
   */
  public long getDateCreated() {
    return dateCreated_;
  }

  public static final int BINARY_FIELD_NUMBER = 3;
  private org.asl19.paskoocheh.BinaryFile binary_;
  /**
   * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
   */
  public boolean hasBinary() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
   */
  public org.asl19.paskoocheh.BinaryFile getBinary() {
    return binary_;
  }
  /**
   * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
   */
  public org.asl19.paskoocheh.BinaryFileOrBuilder getBinaryOrBuilder() {
    return binary_;
  }

  public static final int RATING_FIELD_NUMBER = 4;
  private float rating_;
  /**
   * <code>optional float rating = 4;</code>
   *
   * <pre>
   * Rating for this release
   * </pre>
   */
  public boolean hasRating() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional float rating = 4;</code>
   *
   * <pre>
   * Rating for this release
   * </pre>
   */
  public float getRating() {
    return rating_;
  }

  public static final int DOWNLOAD_COUNT_FIELD_NUMBER = 5;
  private long downloadCount_;
  /**
   * <code>optional int64 download_count = 5;</code>
   *
   * <pre>
   * Number of times this release is downloaded
   * </pre>
   */
  public boolean hasDownloadCount() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional int64 download_count = 5;</code>
   *
   * <pre>
   * Number of times this release is downloaded
   * </pre>
   */
  public long getDownloadCount() {
    return downloadCount_;
  }

  public static final int ICON_FIELD_NUMBER = 6;
  private java.lang.Object icon_;
  /**
   * <code>optional string icon = 6;</code>
   *
   * <pre>
   * URL for the release icon
   * </pre>
   */
  public boolean hasIcon() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string icon = 6;</code>
   *
   * <pre>
   * URL for the release icon
   * </pre>
   */
  public java.lang.String getIcon() {
    java.lang.Object ref = icon_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        icon_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string icon = 6;</code>
   *
   * <pre>
   * URL for the release icon
   * </pre>
   */
  public com.google.protobuf.ByteString
      getIconBytes() {
    java.lang.Object ref = icon_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      icon_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_MODIFIED_FIELD_NUMBER = 7;
  private long dateModified_;
  /**
   * <code>optional int64 date_modified = 7;</code>
   *
   * <pre>
   * Last time this release is modified in unix time
   * </pre>
   */
  public boolean hasDateModified() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional int64 date_modified = 7;</code>
   *
   * <pre>
   * Last time this release is modified in unix time
   * </pre>
   */
  public long getDateModified() {
    return dateModified_;
  }

  public static final int DATE_RELEASED_FIELD_NUMBER = 8;
  private long dateReleased_;
  /**
   * <code>required int64 date_released = 8;</code>
   *
   * <pre>
   * The date this version is released in unix time
   * </pre>
   */
  public boolean hasDateReleased() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>required int64 date_released = 8;</code>
   *
   * <pre>
   * The date this version is released in unix time
   * </pre>
   */
  public long getDateReleased() {
    return dateReleased_;
  }

  public static final int RELEASE_URL_FIELD_NUMBER = 9;
  private java.lang.Object releaseUrl_;
  /**
   * <code>required string release_url = 9;</code>
   *
   * <pre>
   * The original URL for the release
   * </pre>
   */
  public boolean hasReleaseUrl() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>required string release_url = 9;</code>
   *
   * <pre>
   * The original URL for the release
   * </pre>
   */
  public java.lang.String getReleaseUrl() {
    java.lang.Object ref = releaseUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        releaseUrl_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string release_url = 9;</code>
   *
   * <pre>
   * The original URL for the release
   * </pre>
   */
  public com.google.protobuf.ByteString
      getReleaseUrlBytes() {
    java.lang.Object ref = releaseUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      releaseUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCREENSHOTS_FIELD_NUMBER = 10;
  private com.google.protobuf.LazyStringList screenshots_;
  /**
   * <code>repeated string screenshots = 10;</code>
   *
   * <pre>
   * Screen Shots for this release
   * </pre>
   */
  public com.google.protobuf.ProtocolStringList
      getScreenshotsList() {
    return screenshots_;
  }
  /**
   * <code>repeated string screenshots = 10;</code>
   *
   * <pre>
   * Screen Shots for this release
   * </pre>
   */
  public int getScreenshotsCount() {
    return screenshots_.size();
  }
  /**
   * <code>repeated string screenshots = 10;</code>
   *
   * <pre>
   * Screen Shots for this release
   * </pre>
   */
  public java.lang.String getScreenshots(int index) {
    return screenshots_.get(index);
  }
  /**
   * <code>repeated string screenshots = 10;</code>
   *
   * <pre>
   * Screen Shots for this release
   * </pre>
   */
  public com.google.protobuf.ByteString
      getScreenshotsBytes(int index) {
    return screenshots_.getByteString(index);
  }

  public static final int TUTORIALS_FIELD_NUMBER = 11;
  private com.google.protobuf.LazyStringList tutorials_;
  /**
   * <code>repeated string tutorials = 11;</code>
   *
   * <pre>
   * Video Tutorials for this release
   * </pre>
   */
  public com.google.protobuf.ProtocolStringList
      getTutorialsList() {
    return tutorials_;
  }
  /**
   * <code>repeated string tutorials = 11;</code>
   *
   * <pre>
   * Video Tutorials for this release
   * </pre>
   */
  public int getTutorialsCount() {
    return tutorials_.size();
  }
  /**
   * <code>repeated string tutorials = 11;</code>
   *
   * <pre>
   * Video Tutorials for this release
   * </pre>
   */
  public java.lang.String getTutorials(int index) {
    return tutorials_.get(index);
  }
  /**
   * <code>repeated string tutorials = 11;</code>
   *
   * <pre>
   * Video Tutorials for this release
   * </pre>
   */
  public com.google.protobuf.ByteString
      getTutorialsBytes(int index) {
    return tutorials_.getByteString(index);
  }

  public static final int PACKAGE_NAME_FIELD_NUMBER = 12;
  private java.lang.Object packageName_;
  /**
   * <code>optional string package_name = 12;</code>
   *
   * <pre>
   * Android package name - android specific
   * </pre>
   */
  public boolean hasPackageName() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional string package_name = 12;</code>
   *
   * <pre>
   * Android package name - android specific
   * </pre>
   */
  public java.lang.String getPackageName() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        packageName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string package_name = 12;</code>
   *
   * <pre>
   * Android package name - android specific
   * </pre>
   */
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUILD_VERSION_FIELD_NUMBER = 13;
  private int buildVersion_;
  /**
   * <code>optional int32 build_version = 13;</code>
   *
   * <pre>
   * Android build version - android specific
   * </pre>
   */
  public boolean hasBuildVersion() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  /**
   * <code>optional int32 build_version = 13;</code>
   *
   * <pre>
   * Android build version - android specific
   * </pre>
   */
  public int getBuildVersion() {
    return buildVersion_;
  }

  public static final int UPDATE_FIELD_NUMBER = 20;
  private java.util.List<org.asl19.paskoocheh.Message> update_;
  /**
   * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
   *
   * <pre>
   * Release specific updates for the user
   * </pre>
   */
  public java.util.List<org.asl19.paskoocheh.Message> getUpdateList() {
    return update_;
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
   *
   * <pre>
   * Release specific updates for the user
   * </pre>
   */
  public java.util.List<? extends org.asl19.paskoocheh.MessageOrBuilder> 
      getUpdateOrBuilderList() {
    return update_;
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
   *
   * <pre>
   * Release specific updates for the user
   * </pre>
   */
  public int getUpdateCount() {
    return update_.size();
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
   *
   * <pre>
   * Release specific updates for the user
   * </pre>
   */
  public org.asl19.paskoocheh.Message getUpdate(int index) {
    return update_.get(index);
  }
  /**
   * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
   *
   * <pre>
   * Release specific updates for the user
   * </pre>
   */
  public org.asl19.paskoocheh.MessageOrBuilder getUpdateOrBuilder(
      int index) {
    return update_.get(index);
  }

  private void initFields() {
    version_ = "";
    dateCreated_ = 0L;
    binary_ = org.asl19.paskoocheh.BinaryFile.getDefaultInstance();
    rating_ = 0F;
    downloadCount_ = 0L;
    icon_ = "";
    dateModified_ = 0L;
    dateReleased_ = 0L;
    releaseUrl_ = "";
    screenshots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    tutorials_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    packageName_ = "";
    buildVersion_ = 0;
    update_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasVersion()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDateCreated()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasBinary()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDateReleased()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasReleaseUrl()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getBinary().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getUpdateCount(); i++) {
      if (!getUpdate(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getVersionBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, dateCreated_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, binary_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeFloat(4, rating_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt64(5, downloadCount_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBytes(6, getIconBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeInt64(7, dateModified_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeInt64(8, dateReleased_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeBytes(9, getReleaseUrlBytes());
    }
    for (int i = 0; i < screenshots_.size(); i++) {
      output.writeBytes(10, screenshots_.getByteString(i));
    }
    for (int i = 0; i < tutorials_.size(); i++) {
      output.writeBytes(11, tutorials_.getByteString(i));
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeBytes(12, getPackageNameBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeInt32(13, buildVersion_);
    }
    for (int i = 0; i < update_.size(); i++) {
      output.writeMessage(20, update_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getVersionBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, dateCreated_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, binary_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, rating_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, downloadCount_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, getIconBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, dateModified_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, dateReleased_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, getReleaseUrlBytes());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < screenshots_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(screenshots_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getScreenshotsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tutorials_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(tutorials_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getTutorialsList().size();
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, getPackageNameBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, buildVersion_);
    }
    for (int i = 0; i < update_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, update_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.asl19.paskoocheh.Release)) {
      return super.equals(obj);
    }
    org.asl19.paskoocheh.Release other = (org.asl19.paskoocheh.Release) obj;

    boolean result = true;
    result = result && (hasVersion() == other.hasVersion());
    if (hasVersion()) {
      result = result && getVersion()
          .equals(other.getVersion());
    }
    result = result && (hasDateCreated() == other.hasDateCreated());
    if (hasDateCreated()) {
      result = result && (getDateCreated()
          == other.getDateCreated());
    }
    result = result && (hasBinary() == other.hasBinary());
    if (hasBinary()) {
      result = result && getBinary()
          .equals(other.getBinary());
    }
    result = result && (hasRating() == other.hasRating());
    if (hasRating()) {
      result = result && (
          java.lang.Float.floatToIntBits(getRating())
          == java.lang.Float.floatToIntBits(
              other.getRating()));
    }
    result = result && (hasDownloadCount() == other.hasDownloadCount());
    if (hasDownloadCount()) {
      result = result && (getDownloadCount()
          == other.getDownloadCount());
    }
    result = result && (hasIcon() == other.hasIcon());
    if (hasIcon()) {
      result = result && getIcon()
          .equals(other.getIcon());
    }
    result = result && (hasDateModified() == other.hasDateModified());
    if (hasDateModified()) {
      result = result && (getDateModified()
          == other.getDateModified());
    }
    result = result && (hasDateReleased() == other.hasDateReleased());
    if (hasDateReleased()) {
      result = result && (getDateReleased()
          == other.getDateReleased());
    }
    result = result && (hasReleaseUrl() == other.hasReleaseUrl());
    if (hasReleaseUrl()) {
      result = result && getReleaseUrl()
          .equals(other.getReleaseUrl());
    }
    result = result && getScreenshotsList()
        .equals(other.getScreenshotsList());
    result = result && getTutorialsList()
        .equals(other.getTutorialsList());
    result = result && (hasPackageName() == other.hasPackageName());
    if (hasPackageName()) {
      result = result && getPackageName()
          .equals(other.getPackageName());
    }
    result = result && (hasBuildVersion() == other.hasBuildVersion());
    if (hasBuildVersion()) {
      result = result && (getBuildVersion()
          == other.getBuildVersion());
    }
    result = result && getUpdateList()
        .equals(other.getUpdateList());
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    if (hasDateCreated()) {
      hash = (37 * hash) + DATE_CREATED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDateCreated());
    }
    if (hasBinary()) {
      hash = (37 * hash) + BINARY_FIELD_NUMBER;
      hash = (53 * hash) + getBinary().hashCode();
    }
    if (hasRating()) {
      hash = (37 * hash) + RATING_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getRating());
    }
    if (hasDownloadCount()) {
      hash = (37 * hash) + DOWNLOAD_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDownloadCount());
    }
    if (hasIcon()) {
      hash = (37 * hash) + ICON_FIELD_NUMBER;
      hash = (53 * hash) + getIcon().hashCode();
    }
    if (hasDateModified()) {
      hash = (37 * hash) + DATE_MODIFIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDateModified());
    }
    if (hasDateReleased()) {
      hash = (37 * hash) + DATE_RELEASED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDateReleased());
    }
    if (hasReleaseUrl()) {
      hash = (37 * hash) + RELEASE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getReleaseUrl().hashCode();
    }
    if (getScreenshotsCount() > 0) {
      hash = (37 * hash) + SCREENSHOTS_FIELD_NUMBER;
      hash = (53 * hash) + getScreenshotsList().hashCode();
    }
    if (getTutorialsCount() > 0) {
      hash = (37 * hash) + TUTORIALS_FIELD_NUMBER;
      hash = (53 * hash) + getTutorialsList().hashCode();
    }
    if (hasPackageName()) {
      hash = (37 * hash) + PACKAGE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPackageName().hashCode();
    }
    if (hasBuildVersion()) {
      hash = (37 * hash) + BUILD_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getBuildVersion();
    }
    if (getUpdateCount() > 0) {
      hash = (37 * hash) + UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.asl19.paskoocheh.Release parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.asl19.paskoocheh.Release parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Release parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.asl19.paskoocheh.Release parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Release parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.asl19.paskoocheh.Release parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Release parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.asl19.paskoocheh.Release parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.asl19.paskoocheh.Release parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.asl19.paskoocheh.Release parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.asl19.paskoocheh.Release prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.asl19.paskoocheh.Release}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.asl19.paskoocheh.Release)
      org.asl19.paskoocheh.ReleaseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Release_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Release_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.asl19.paskoocheh.Release.class, org.asl19.paskoocheh.Release.Builder.class);
    }

    // Construct using org.asl19.paskoocheh.Release.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getBinaryFieldBuilder();
        getUpdateFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      version_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      dateCreated_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (binaryBuilder_ == null) {
        binary_ = org.asl19.paskoocheh.BinaryFile.getDefaultInstance();
      } else {
        binaryBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      rating_ = 0F;
      bitField0_ = (bitField0_ & ~0x00000008);
      downloadCount_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      icon_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      dateModified_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      dateReleased_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000080);
      releaseUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      screenshots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000200);
      tutorials_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000400);
      packageName_ = "";
      bitField0_ = (bitField0_ & ~0x00000800);
      buildVersion_ = 0;
      bitField0_ = (bitField0_ & ~0x00001000);
      if (updateBuilder_ == null) {
        update_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
      } else {
        updateBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.asl19.paskoocheh.Paskoocheh.internal_static_org_asl19_paskoocheh_Release_descriptor;
    }

    public org.asl19.paskoocheh.Release getDefaultInstanceForType() {
      return org.asl19.paskoocheh.Release.getDefaultInstance();
    }

    public org.asl19.paskoocheh.Release build() {
      org.asl19.paskoocheh.Release result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.asl19.paskoocheh.Release buildPartial() {
      org.asl19.paskoocheh.Release result = new org.asl19.paskoocheh.Release(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.version_ = version_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.dateCreated_ = dateCreated_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (binaryBuilder_ == null) {
        result.binary_ = binary_;
      } else {
        result.binary_ = binaryBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.rating_ = rating_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.downloadCount_ = downloadCount_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.icon_ = icon_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.dateModified_ = dateModified_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.dateReleased_ = dateReleased_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.releaseUrl_ = releaseUrl_;
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        screenshots_ = screenshots_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000200);
      }
      result.screenshots_ = screenshots_;
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        tutorials_ = tutorials_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000400);
      }
      result.tutorials_ = tutorials_;
      if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
        to_bitField0_ |= 0x00000200;
      }
      result.packageName_ = packageName_;
      if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
        to_bitField0_ |= 0x00000400;
      }
      result.buildVersion_ = buildVersion_;
      if (updateBuilder_ == null) {
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          update_ = java.util.Collections.unmodifiableList(update_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.update_ = update_;
      } else {
        result.update_ = updateBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.asl19.paskoocheh.Release) {
        return mergeFrom((org.asl19.paskoocheh.Release)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.asl19.paskoocheh.Release other) {
      if (other == org.asl19.paskoocheh.Release.getDefaultInstance()) return this;
      if (other.hasVersion()) {
        bitField0_ |= 0x00000001;
        version_ = other.version_;
        onChanged();
      }
      if (other.hasDateCreated()) {
        setDateCreated(other.getDateCreated());
      }
      if (other.hasBinary()) {
        mergeBinary(other.getBinary());
      }
      if (other.hasRating()) {
        setRating(other.getRating());
      }
      if (other.hasDownloadCount()) {
        setDownloadCount(other.getDownloadCount());
      }
      if (other.hasIcon()) {
        bitField0_ |= 0x00000020;
        icon_ = other.icon_;
        onChanged();
      }
      if (other.hasDateModified()) {
        setDateModified(other.getDateModified());
      }
      if (other.hasDateReleased()) {
        setDateReleased(other.getDateReleased());
      }
      if (other.hasReleaseUrl()) {
        bitField0_ |= 0x00000100;
        releaseUrl_ = other.releaseUrl_;
        onChanged();
      }
      if (!other.screenshots_.isEmpty()) {
        if (screenshots_.isEmpty()) {
          screenshots_ = other.screenshots_;
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          ensureScreenshotsIsMutable();
          screenshots_.addAll(other.screenshots_);
        }
        onChanged();
      }
      if (!other.tutorials_.isEmpty()) {
        if (tutorials_.isEmpty()) {
          tutorials_ = other.tutorials_;
          bitField0_ = (bitField0_ & ~0x00000400);
        } else {
          ensureTutorialsIsMutable();
          tutorials_.addAll(other.tutorials_);
        }
        onChanged();
      }
      if (other.hasPackageName()) {
        bitField0_ |= 0x00000800;
        packageName_ = other.packageName_;
        onChanged();
      }
      if (other.hasBuildVersion()) {
        setBuildVersion(other.getBuildVersion());
      }
      if (updateBuilder_ == null) {
        if (!other.update_.isEmpty()) {
          if (update_.isEmpty()) {
            update_ = other.update_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureUpdateIsMutable();
            update_.addAll(other.update_);
          }
          onChanged();
        }
      } else {
        if (!other.update_.isEmpty()) {
          if (updateBuilder_.isEmpty()) {
            updateBuilder_.dispose();
            updateBuilder_ = null;
            update_ = other.update_;
            bitField0_ = (bitField0_ & ~0x00002000);
            updateBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getUpdateFieldBuilder() : null;
          } else {
            updateBuilder_.addAllMessages(other.update_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasVersion()) {
        
        return false;
      }
      if (!hasDateCreated()) {
        
        return false;
      }
      if (!hasBinary()) {
        
        return false;
      }
      if (!hasDateReleased()) {
        
        return false;
      }
      if (!hasReleaseUrl()) {
        
        return false;
      }
      if (!getBinary().isInitialized()) {
        
        return false;
      }
      for (int i = 0; i < getUpdateCount(); i++) {
        if (!getUpdate(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.asl19.paskoocheh.Release parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.asl19.paskoocheh.Release) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object version_ = "";
    /**
     * <code>required string version = 1;</code>
     *
     * <pre>
     * Version of the release
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string version = 1;</code>
     *
     * <pre>
     * Version of the release
     * </pre>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string version = 1;</code>
     *
     * <pre>
     * Version of the release
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string version = 1;</code>
     *
     * <pre>
     * Version of the release
     * </pre>
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string version = 1;</code>
     *
     * <pre>
     * Version of the release
     * </pre>
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>required string version = 1;</code>
     *
     * <pre>
     * Version of the release
     * </pre>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      version_ = value;
      onChanged();
      return this;
    }

    private long dateCreated_ ;
    /**
     * <code>required int64 date_created = 2;</code>
     *
     * <pre>
     * Date the file uploaded in unix time
     * </pre>
     */
    public boolean hasDateCreated() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 date_created = 2;</code>
     *
     * <pre>
     * Date the file uploaded in unix time
     * </pre>
     */
    public long getDateCreated() {
      return dateCreated_;
    }
    /**
     * <code>required int64 date_created = 2;</code>
     *
     * <pre>
     * Date the file uploaded in unix time
     * </pre>
     */
    public Builder setDateCreated(long value) {
      bitField0_ |= 0x00000002;
      dateCreated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 date_created = 2;</code>
     *
     * <pre>
     * Date the file uploaded in unix time
     * </pre>
     */
    public Builder clearDateCreated() {
      bitField0_ = (bitField0_ & ~0x00000002);
      dateCreated_ = 0L;
      onChanged();
      return this;
    }

    private org.asl19.paskoocheh.BinaryFile binary_ = org.asl19.paskoocheh.BinaryFile.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        org.asl19.paskoocheh.BinaryFile, org.asl19.paskoocheh.BinaryFile.Builder, org.asl19.paskoocheh.BinaryFileOrBuilder> binaryBuilder_;
    /**
     * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
     */
    public boolean hasBinary() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
     */
    public org.asl19.paskoocheh.BinaryFile getBinary() {
      if (binaryBuilder_ == null) {
        return binary_;
      } else {
        return binaryBuilder_.getMessage();
      }
    }
    /**
     * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
     */
    public Builder setBinary(org.asl19.paskoocheh.BinaryFile value) {
      if (binaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        binary_ = value;
        onChanged();
      } else {
        binaryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
     */
    public Builder setBinary(
        org.asl19.paskoocheh.BinaryFile.Builder builderForValue) {
      if (binaryBuilder_ == null) {
        binary_ = builderForValue.build();
        onChanged();
      } else {
        binaryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
     */
    public Builder mergeBinary(org.asl19.paskoocheh.BinaryFile value) {
      if (binaryBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            binary_ != org.asl19.paskoocheh.BinaryFile.getDefaultInstance()) {
          binary_ =
            org.asl19.paskoocheh.BinaryFile.newBuilder(binary_).mergeFrom(value).buildPartial();
        } else {
          binary_ = value;
        }
        onChanged();
      } else {
        binaryBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
     */
    public Builder clearBinary() {
      if (binaryBuilder_ == null) {
        binary_ = org.asl19.paskoocheh.BinaryFile.getDefaultInstance();
        onChanged();
      } else {
        binaryBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
     */
    public org.asl19.paskoocheh.BinaryFile.Builder getBinaryBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getBinaryFieldBuilder().getBuilder();
    }
    /**
     * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
     */
    public org.asl19.paskoocheh.BinaryFileOrBuilder getBinaryOrBuilder() {
      if (binaryBuilder_ != null) {
        return binaryBuilder_.getMessageOrBuilder();
      } else {
        return binary_;
      }
    }
    /**
     * <code>required .org.asl19.paskoocheh.BinaryFile binary = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.asl19.paskoocheh.BinaryFile, org.asl19.paskoocheh.BinaryFile.Builder, org.asl19.paskoocheh.BinaryFileOrBuilder> 
        getBinaryFieldBuilder() {
      if (binaryBuilder_ == null) {
        binaryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.asl19.paskoocheh.BinaryFile, org.asl19.paskoocheh.BinaryFile.Builder, org.asl19.paskoocheh.BinaryFileOrBuilder>(
                getBinary(),
                getParentForChildren(),
                isClean());
        binary_ = null;
      }
      return binaryBuilder_;
    }

    private float rating_ ;
    /**
     * <code>optional float rating = 4;</code>
     *
     * <pre>
     * Rating for this release
     * </pre>
     */
    public boolean hasRating() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float rating = 4;</code>
     *
     * <pre>
     * Rating for this release
     * </pre>
     */
    public float getRating() {
      return rating_;
    }
    /**
     * <code>optional float rating = 4;</code>
     *
     * <pre>
     * Rating for this release
     * </pre>
     */
    public Builder setRating(float value) {
      bitField0_ |= 0x00000008;
      rating_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float rating = 4;</code>
     *
     * <pre>
     * Rating for this release
     * </pre>
     */
    public Builder clearRating() {
      bitField0_ = (bitField0_ & ~0x00000008);
      rating_ = 0F;
      onChanged();
      return this;
    }

    private long downloadCount_ ;
    /**
     * <code>optional int64 download_count = 5;</code>
     *
     * <pre>
     * Number of times this release is downloaded
     * </pre>
     */
    public boolean hasDownloadCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 download_count = 5;</code>
     *
     * <pre>
     * Number of times this release is downloaded
     * </pre>
     */
    public long getDownloadCount() {
      return downloadCount_;
    }
    /**
     * <code>optional int64 download_count = 5;</code>
     *
     * <pre>
     * Number of times this release is downloaded
     * </pre>
     */
    public Builder setDownloadCount(long value) {
      bitField0_ |= 0x00000010;
      downloadCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 download_count = 5;</code>
     *
     * <pre>
     * Number of times this release is downloaded
     * </pre>
     */
    public Builder clearDownloadCount() {
      bitField0_ = (bitField0_ & ~0x00000010);
      downloadCount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object icon_ = "";
    /**
     * <code>optional string icon = 6;</code>
     *
     * <pre>
     * URL for the release icon
     * </pre>
     */
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string icon = 6;</code>
     *
     * <pre>
     * URL for the release icon
     * </pre>
     */
    public java.lang.String getIcon() {
      java.lang.Object ref = icon_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icon_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string icon = 6;</code>
     *
     * <pre>
     * URL for the release icon
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIconBytes() {
      java.lang.Object ref = icon_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string icon = 6;</code>
     *
     * <pre>
     * URL for the release icon
     * </pre>
     */
    public Builder setIcon(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      icon_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string icon = 6;</code>
     *
     * <pre>
     * URL for the release icon
     * </pre>
     */
    public Builder clearIcon() {
      bitField0_ = (bitField0_ & ~0x00000020);
      icon_ = getDefaultInstance().getIcon();
      onChanged();
      return this;
    }
    /**
     * <code>optional string icon = 6;</code>
     *
     * <pre>
     * URL for the release icon
     * </pre>
     */
    public Builder setIconBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      icon_ = value;
      onChanged();
      return this;
    }

    private long dateModified_ ;
    /**
     * <code>optional int64 date_modified = 7;</code>
     *
     * <pre>
     * Last time this release is modified in unix time
     * </pre>
     */
    public boolean hasDateModified() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 date_modified = 7;</code>
     *
     * <pre>
     * Last time this release is modified in unix time
     * </pre>
     */
    public long getDateModified() {
      return dateModified_;
    }
    /**
     * <code>optional int64 date_modified = 7;</code>
     *
     * <pre>
     * Last time this release is modified in unix time
     * </pre>
     */
    public Builder setDateModified(long value) {
      bitField0_ |= 0x00000040;
      dateModified_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 date_modified = 7;</code>
     *
     * <pre>
     * Last time this release is modified in unix time
     * </pre>
     */
    public Builder clearDateModified() {
      bitField0_ = (bitField0_ & ~0x00000040);
      dateModified_ = 0L;
      onChanged();
      return this;
    }

    private long dateReleased_ ;
    /**
     * <code>required int64 date_released = 8;</code>
     *
     * <pre>
     * The date this version is released in unix time
     * </pre>
     */
    public boolean hasDateReleased() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int64 date_released = 8;</code>
     *
     * <pre>
     * The date this version is released in unix time
     * </pre>
     */
    public long getDateReleased() {
      return dateReleased_;
    }
    /**
     * <code>required int64 date_released = 8;</code>
     *
     * <pre>
     * The date this version is released in unix time
     * </pre>
     */
    public Builder setDateReleased(long value) {
      bitField0_ |= 0x00000080;
      dateReleased_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 date_released = 8;</code>
     *
     * <pre>
     * The date this version is released in unix time
     * </pre>
     */
    public Builder clearDateReleased() {
      bitField0_ = (bitField0_ & ~0x00000080);
      dateReleased_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object releaseUrl_ = "";
    /**
     * <code>required string release_url = 9;</code>
     *
     * <pre>
     * The original URL for the release
     * </pre>
     */
    public boolean hasReleaseUrl() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string release_url = 9;</code>
     *
     * <pre>
     * The original URL for the release
     * </pre>
     */
    public java.lang.String getReleaseUrl() {
      java.lang.Object ref = releaseUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          releaseUrl_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string release_url = 9;</code>
     *
     * <pre>
     * The original URL for the release
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReleaseUrlBytes() {
      java.lang.Object ref = releaseUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        releaseUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string release_url = 9;</code>
     *
     * <pre>
     * The original URL for the release
     * </pre>
     */
    public Builder setReleaseUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      releaseUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string release_url = 9;</code>
     *
     * <pre>
     * The original URL for the release
     * </pre>
     */
    public Builder clearReleaseUrl() {
      bitField0_ = (bitField0_ & ~0x00000100);
      releaseUrl_ = getDefaultInstance().getReleaseUrl();
      onChanged();
      return this;
    }
    /**
     * <code>required string release_url = 9;</code>
     *
     * <pre>
     * The original URL for the release
     * </pre>
     */
    public Builder setReleaseUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      releaseUrl_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList screenshots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureScreenshotsIsMutable() {
      if (!((bitField0_ & 0x00000200) == 0x00000200)) {
        screenshots_ = new com.google.protobuf.LazyStringArrayList(screenshots_);
        bitField0_ |= 0x00000200;
       }
    }
    /**
     * <code>repeated string screenshots = 10;</code>
     *
     * <pre>
     * Screen Shots for this release
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getScreenshotsList() {
      return screenshots_.getUnmodifiableView();
    }
    /**
     * <code>repeated string screenshots = 10;</code>
     *
     * <pre>
     * Screen Shots for this release
     * </pre>
     */
    public int getScreenshotsCount() {
      return screenshots_.size();
    }
    /**
     * <code>repeated string screenshots = 10;</code>
     *
     * <pre>
     * Screen Shots for this release
     * </pre>
     */
    public java.lang.String getScreenshots(int index) {
      return screenshots_.get(index);
    }
    /**
     * <code>repeated string screenshots = 10;</code>
     *
     * <pre>
     * Screen Shots for this release
     * </pre>
     */
    public com.google.protobuf.ByteString
        getScreenshotsBytes(int index) {
      return screenshots_.getByteString(index);
    }
    /**
     * <code>repeated string screenshots = 10;</code>
     *
     * <pre>
     * Screen Shots for this release
     * </pre>
     */
    public Builder setScreenshots(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureScreenshotsIsMutable();
      screenshots_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string screenshots = 10;</code>
     *
     * <pre>
     * Screen Shots for this release
     * </pre>
     */
    public Builder addScreenshots(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureScreenshotsIsMutable();
      screenshots_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string screenshots = 10;</code>
     *
     * <pre>
     * Screen Shots for this release
     * </pre>
     */
    public Builder addAllScreenshots(
        java.lang.Iterable<java.lang.String> values) {
      ensureScreenshotsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, screenshots_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string screenshots = 10;</code>
     *
     * <pre>
     * Screen Shots for this release
     * </pre>
     */
    public Builder clearScreenshots() {
      screenshots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string screenshots = 10;</code>
     *
     * <pre>
     * Screen Shots for this release
     * </pre>
     */
    public Builder addScreenshotsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureScreenshotsIsMutable();
      screenshots_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList tutorials_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTutorialsIsMutable() {
      if (!((bitField0_ & 0x00000400) == 0x00000400)) {
        tutorials_ = new com.google.protobuf.LazyStringArrayList(tutorials_);
        bitField0_ |= 0x00000400;
       }
    }
    /**
     * <code>repeated string tutorials = 11;</code>
     *
     * <pre>
     * Video Tutorials for this release
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getTutorialsList() {
      return tutorials_.getUnmodifiableView();
    }
    /**
     * <code>repeated string tutorials = 11;</code>
     *
     * <pre>
     * Video Tutorials for this release
     * </pre>
     */
    public int getTutorialsCount() {
      return tutorials_.size();
    }
    /**
     * <code>repeated string tutorials = 11;</code>
     *
     * <pre>
     * Video Tutorials for this release
     * </pre>
     */
    public java.lang.String getTutorials(int index) {
      return tutorials_.get(index);
    }
    /**
     * <code>repeated string tutorials = 11;</code>
     *
     * <pre>
     * Video Tutorials for this release
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTutorialsBytes(int index) {
      return tutorials_.getByteString(index);
    }
    /**
     * <code>repeated string tutorials = 11;</code>
     *
     * <pre>
     * Video Tutorials for this release
     * </pre>
     */
    public Builder setTutorials(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTutorialsIsMutable();
      tutorials_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tutorials = 11;</code>
     *
     * <pre>
     * Video Tutorials for this release
     * </pre>
     */
    public Builder addTutorials(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTutorialsIsMutable();
      tutorials_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tutorials = 11;</code>
     *
     * <pre>
     * Video Tutorials for this release
     * </pre>
     */
    public Builder addAllTutorials(
        java.lang.Iterable<java.lang.String> values) {
      ensureTutorialsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tutorials_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tutorials = 11;</code>
     *
     * <pre>
     * Video Tutorials for this release
     * </pre>
     */
    public Builder clearTutorials() {
      tutorials_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tutorials = 11;</code>
     *
     * <pre>
     * Video Tutorials for this release
     * </pre>
     */
    public Builder addTutorialsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTutorialsIsMutable();
      tutorials_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object packageName_ = "";
    /**
     * <code>optional string package_name = 12;</code>
     *
     * <pre>
     * Android package name - android specific
     * </pre>
     */
    public boolean hasPackageName() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string package_name = 12;</code>
     *
     * <pre>
     * Android package name - android specific
     * </pre>
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packageName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string package_name = 12;</code>
     *
     * <pre>
     * Android package name - android specific
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string package_name = 12;</code>
     *
     * <pre>
     * Android package name - android specific
     * </pre>
     */
    public Builder setPackageName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      packageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string package_name = 12;</code>
     *
     * <pre>
     * Android package name - android specific
     * </pre>
     */
    public Builder clearPackageName() {
      bitField0_ = (bitField0_ & ~0x00000800);
      packageName_ = getDefaultInstance().getPackageName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string package_name = 12;</code>
     *
     * <pre>
     * Android package name - android specific
     * </pre>
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      packageName_ = value;
      onChanged();
      return this;
    }

    private int buildVersion_ ;
    /**
     * <code>optional int32 build_version = 13;</code>
     *
     * <pre>
     * Android build version - android specific
     * </pre>
     */
    public boolean hasBuildVersion() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 build_version = 13;</code>
     *
     * <pre>
     * Android build version - android specific
     * </pre>
     */
    public int getBuildVersion() {
      return buildVersion_;
    }
    /**
     * <code>optional int32 build_version = 13;</code>
     *
     * <pre>
     * Android build version - android specific
     * </pre>
     */
    public Builder setBuildVersion(int value) {
      bitField0_ |= 0x00001000;
      buildVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 build_version = 13;</code>
     *
     * <pre>
     * Android build version - android specific
     * </pre>
     */
    public Builder clearBuildVersion() {
      bitField0_ = (bitField0_ & ~0x00001000);
      buildVersion_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<org.asl19.paskoocheh.Message> update_ =
      java.util.Collections.emptyList();
    private void ensureUpdateIsMutable() {
      if (!((bitField0_ & 0x00002000) == 0x00002000)) {
        update_ = new java.util.ArrayList<org.asl19.paskoocheh.Message>(update_);
        bitField0_ |= 0x00002000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.asl19.paskoocheh.Message, org.asl19.paskoocheh.Message.Builder, org.asl19.paskoocheh.MessageOrBuilder> updateBuilder_;

    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public java.util.List<org.asl19.paskoocheh.Message> getUpdateList() {
      if (updateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(update_);
      } else {
        return updateBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public int getUpdateCount() {
      if (updateBuilder_ == null) {
        return update_.size();
      } else {
        return updateBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public org.asl19.paskoocheh.Message getUpdate(int index) {
      if (updateBuilder_ == null) {
        return update_.get(index);
      } else {
        return updateBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public Builder setUpdate(
        int index, org.asl19.paskoocheh.Message value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.set(index, value);
        onChanged();
      } else {
        updateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public Builder setUpdate(
        int index, org.asl19.paskoocheh.Message.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.set(index, builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public Builder addUpdate(org.asl19.paskoocheh.Message value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.add(value);
        onChanged();
      } else {
        updateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public Builder addUpdate(
        int index, org.asl19.paskoocheh.Message value) {
      if (updateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateIsMutable();
        update_.add(index, value);
        onChanged();
      } else {
        updateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public Builder addUpdate(
        org.asl19.paskoocheh.Message.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.add(builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public Builder addUpdate(
        int index, org.asl19.paskoocheh.Message.Builder builderForValue) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.add(index, builderForValue.build());
        onChanged();
      } else {
        updateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public Builder addAllUpdate(
        java.lang.Iterable<? extends org.asl19.paskoocheh.Message> values) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, update_);
        onChanged();
      } else {
        updateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public Builder clearUpdate() {
      if (updateBuilder_ == null) {
        update_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
      } else {
        updateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public Builder removeUpdate(int index) {
      if (updateBuilder_ == null) {
        ensureUpdateIsMutable();
        update_.remove(index);
        onChanged();
      } else {
        updateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public org.asl19.paskoocheh.Message.Builder getUpdateBuilder(
        int index) {
      return getUpdateFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public org.asl19.paskoocheh.MessageOrBuilder getUpdateOrBuilder(
        int index) {
      if (updateBuilder_ == null) {
        return update_.get(index);  } else {
        return updateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public java.util.List<? extends org.asl19.paskoocheh.MessageOrBuilder> 
         getUpdateOrBuilderList() {
      if (updateBuilder_ != null) {
        return updateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(update_);
      }
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public org.asl19.paskoocheh.Message.Builder addUpdateBuilder() {
      return getUpdateFieldBuilder().addBuilder(
          org.asl19.paskoocheh.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public org.asl19.paskoocheh.Message.Builder addUpdateBuilder(
        int index) {
      return getUpdateFieldBuilder().addBuilder(
          index, org.asl19.paskoocheh.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .org.asl19.paskoocheh.Message update = 20;</code>
     *
     * <pre>
     * Release specific updates for the user
     * </pre>
     */
    public java.util.List<org.asl19.paskoocheh.Message.Builder> 
         getUpdateBuilderList() {
      return getUpdateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.asl19.paskoocheh.Message, org.asl19.paskoocheh.Message.Builder, org.asl19.paskoocheh.MessageOrBuilder> 
        getUpdateFieldBuilder() {
      if (updateBuilder_ == null) {
        updateBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.asl19.paskoocheh.Message, org.asl19.paskoocheh.Message.Builder, org.asl19.paskoocheh.MessageOrBuilder>(
                update_,
                ((bitField0_ & 0x00002000) == 0x00002000),
                getParentForChildren(),
                isClean());
        update_ = null;
      }
      return updateBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.asl19.paskoocheh.Release)
  }

  static {
    defaultInstance = new Release(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.asl19.paskoocheh.Release)
}

