// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paskoocheh.proto

package org.asl19.paskoocheh;

public interface TranslationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.asl19.paskoocheh.Translation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string lang = 1;</code>
   *
   * <pre>
   * Language of the translation
   * </pre>
   */
  boolean hasLang();
  /**
   * <code>required string lang = 1;</code>
   *
   * <pre>
   * Language of the translation
   * </pre>
   */
  java.lang.String getLang();
  /**
   * <code>required string lang = 1;</code>
   *
   * <pre>
   * Language of the translation
   * </pre>
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <code>required string name = 2;</code>
   *
   * <pre>
   * Name if the tool in the lang
   * </pre>
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   *
   * <pre>
   * Name if the tool in the lang
   * </pre>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   *
   * <pre>
   * Name if the tool in the lang
   * </pre>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string description = 3;</code>
   *
   * <pre>
   * Description for the tool in the lang
   * </pre>
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 3;</code>
   *
   * <pre>
   * Description for the tool in the lang
   * </pre>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 3;</code>
   *
   * <pre>
   * Description for the tool in the lang
   * </pre>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
